insert into STTM_UPLOAD_CUSTOMER (
ACTION_CODE,         --1   ACTION_CODE
ADDRESS_LINE1,         --2   ADDRESS_LINE1
ADDRESS_LINE2,         --3   ADDRESS_LINE2
ADDRESS_LINE3,         --4   ADDRESS_LINE3
ADDRESS_LINE4,         --5   ADDRESS_LINE4
ALG_ID,         --6   ALG_ID
ALLOW_VRTL_ACCNTS,         --7   ALLOW_VRTL_ACCNTS
AML_CUSTOMER_GRP,         --8   AML_CUSTOMER_GRP
AML_REQUIRED,         --9   AML_REQUIRED
AR_AP_TRACKING,         --10   AR_AP_TRACKING
AUTOGEN_STMTPLAN,         --11   AUTOGEN_STMTPLAN
AUTO_CREATE_ACCOUNT,         --12   AUTO_CREATE_ACCOUNT
AUTO_CUST_AC_NO,         --13   AUTO_CUST_AC_NO
BRANCH_CODE,         --14   BRANCH_CODE
CAS_CUST,         --15   CAS_CUST
CHARGE_GROUP,         --16   CHARGE_GROUP
CHECKER_DT_STAMP,         --17   CHECKER_DT_STAMP
CHECKER_ID,         --18   CHECKER_ID
CHK_DIGIT_VALID_REQD,         --19   CHK_DIGIT_VALID_REQD
CIF_CREATION_DATE,         --20   CIF_CREATION_DATE
CIF_STATUS,         --21   CIF_STATUS
CIF_STATUS_SINCE,         --22   CIF_STATUS_SINCE
CLS_CCY_ALLOWED,         --23   CLS_CCY_ALLOWED
CLS_PARTICIPANT,         --24   CLS_PARTICIPANT
CONSOL_TAX_CERT_REQD,         --25   CONSOL_TAX_CERT_REQD
CONVERSION_STATUS_FLAG,         --26   CONVERSION_STATUS_FLAG
COUNTRY,         --27   COUNTRY
CREDIT_RATING,         --28   CREDIT_RATING
CRM_CUSTOMER,         --29   CRM_CUSTOMER
CRS_TYPE,         --30   CRS_TYPE
CUSTOMER_CATEGORY,         --31   CUSTOMER_CATEGORY
CUSTOMER_NAME1,         --32   CUSTOMER_NAME1
CUSTOMER_NO,         --33   CUSTOMER_NO
CUSTOMER_TYPE,         --34   CUSTOMER_TYPE
CUST_CLASSIFICATION,         --35   CUST_CLASSIFICATION
CUST_CLG_GROUP,         --36   CUST_CLG_GROUP
CUST_UNADVISED,         --37   CUST_UNADVISED
DEBTOR_CATEGORY,         --38   DEBTOR_CATEGORY
DECEASED,         --39   DECEASED
DEFAULT_MEDIA,         --40   DEFAULT_MEDIA
ELCM_CUSTOMER,         --41   ELCM_CUSTOMER
ERR_MSG,         --42   ERR_MSG
EXPOSURE_CATEGORY,         --43   EXPOSURE_CATEGORY
EXPOSURE_COUNTRY,         --44   EXPOSURE_COUNTRY
EXT_REF_NO,         --45   EXT_REF_NO
FAX_NUMBER,         --46   FAX_NUMBER
FREQUENCY,         --47   FREQUENCY
FROZEN,         --48   FROZEN
FT_ACCTING_AS_OF,         --49   FT_ACCTING_AS_OF
FULL_NAME,         --50   FULL_NAME
FX_CLEAN_RISK_LIMIT,         --51   FX_CLEAN_RISK_LIMIT
FX_CUST_CLEAN_RISK_LIMIT,         --52   FX_CUST_CLEAN_RISK_LIMIT
FX_NETTING_CUSTOMER,         --53   FX_NETTING_CUSTOMER
GENERATE_MT920,         --54   GENERATE_MT920
GROUP_CODE,         --55   GROUP_CODE
HO_AC_NO,         --56   HO_AC_NO
INDIVIDUAL_TAX_CERT_REQD,         --57   INDIVIDUAL_TAX_CERT_REQD
INTRODUCER,         --58   INTRODUCER
INVEST_CUST,         --59   INVEST_CUST
ISSUER_CUSTOMER,         --60   ISSUER_CUSTOMER
JOINT_VENTURE,         --61   JOINT_VENTURE
KYC_DETAILS,         --62   KYC_DETAILS
KYC_REF_NO,         --63   KYC_REF_NO
LANGUAGE,         --64   LANGUAGE
LC_COLLATERAL_PCT,         --65   LC_COLLATERAL_PCT
LIABILITY_NO,         --66   LIABILITY_NO
LIAB_BR,         --67   LIAB_BR
LIAB_NODE,         --68   LIAB_NODE
LIAB_UNADVISED,         --69   LIAB_UNADVISED
LIMIT_CCY,         --70   LIMIT_CCY
LOCAL_BRANCH,         --71   LOCAL_BRANCH
LOC_CODE,         --72   LOC_CODE
MAILERS_REQUIRED,         --73   MAILERS_REQUIRED
MAINTENANCE_SEQ_NO,         --74   MAINTENANCE_SEQ_NO
MAKER_DT_STAMP,         --75   MAKER_DT_STAMP
MAKER_ID,         --76   MAKER_ID
MFI_CUSTOMER,         --77   MFI_CUSTOMER
NATIONALITY,         --78   NATIONALITY
OVERALL_LIMIT,         --79   OVERALL_LIMIT
PAST_DUE_FLAG,         --80   PAST_DUE_FLAG
PINCODE,         --81   PINCODE
PRIVATE_CUSTOMER,         --82   PRIVATE_CUSTOMER
REVISION_DATE,         --83   REVISION_DATE
RISK_CATEGORY,         --84   RISK_CATEGORY
RISK_PROFILE,         --85   RISK_PROFILE
RM_ID,         --86   RM_ID
RP_CUSTOMER,         --87   RP_CUSTOMER
SEC_CLEAN_RISK_LIMIT,         --88   SEC_CLEAN_RISK_LIMIT
SEC_CUST_CLEAN_RISK_LIMIT,         --89   SEC_CUST_CLEAN_RISK_LIMIT
SEC_CUST_PSTL_RISK_LIMIT,         --90   SEC_CUST_PSTL_RISK_LIMIT
SEC_PSTL_RISK_LIMIT,         --91   SEC_PSTL_RISK_LIMIT
SHORT_NAME,         --92   SHORT_NAME
SHORT_NAME2,         --93   SHORT_NAME2
SOURCE_CODE,         --94   SOURCE_CODE
SOURCE_SEQ_NO,         --95   SOURCE_SEQ_NO
SPECIAL_CUST,         --96   SPECIAL_CUST
SSN,         --97   SSN
STAFF,         --98   STAFF
STMT_DAY,         --99   STMT_DAY
SWIFT_CODE,         --100   SWIFT_CODE
TAXID_NO,         --101   TAXID_NO
TAX_CNTRY,         --102   TAX_CNTRY
TAX_GROUP,         --103   TAX_GROUP
TRACK_LIMITS,         --104   TRACK_LIMITS
TREASURY_CUSTOMER,         --105   TREASURY_CUSTOMER
UDF_1,         --106   UDF_1
UDF_2,         --107   UDF_2
UDF_3,         --108   UDF_3
UDF_4,         --109   UDF_4
UDF_5,         --110   UDF_5
UNIQUE_ID_NAME,         --111   UNIQUE_ID_NAME
UNIQUE_ID_VALUE,         --112   UNIQUE_ID_VALUE
UTILITY_PROVIDER,         --113   UTILITY_PROVIDER
UTILITY_PROVIDER_ID,         --114   UTILITY_PROVIDER_ID
UTILITY_PROVIDER_TYPE,         --115   UTILITY_PROVIDER_TYPE
VRTL_CUSTOMER_ID,         --116   VRTL_CUSTOMER_ID
WHEREABOUTS_UNKNOWN,         --117   WHEREABOUTS_UNKNOWN
WHT_PCT,         --118   WHT_PCT
WITHHOLDING_TAX)         --119   WITHHOLDING_TAX


select 
'NEW'  ACTION_CODE,         --1   ACTION_CODE
trim(ADDRESS_LINE1)  ADDRESS_LINE1,         --2   ADDRESS_LINE1
trim(ADDRESS_LINE2)  ADDRESS_LINE2,         --3   ADDRESS_LINE2
trim(ADDRESS_LINE3)  ADDRESS_LINE3,         --4   ADDRESS_LINE3
trim(ADDRESS_LINE4)  ADDRESS_LINE4,         --5   ADDRESS_LINE4
trim(ALG_ID)  ALG_ID,         --6   ALG_ID
trim(ALLOW_VRTL_ACCNTS)  ALLOW_VRTL_ACCNTS,         --7   ALLOW_VRTL_ACCNTS
trim(AML_CUSTOMER_GRP)  AML_CUSTOMER_GRP,         --8   AML_CUSTOMER_GRP
trim(AML_REQUIRED)  AML_REQUIRED,         --9   AML_REQUIRED
trim(AR_AP_TRACKING)  AR_AP_TRACKING,         --10   AR_AP_TRACKING
trim(AUTOGEN_STMTPLAN)  AUTOGEN_STMTPLAN,         --11   AUTOGEN_STMTPLAN
trim(AUTO_CREATE_ACCOUNT)  AUTO_CREATE_ACCOUNT,         --12   AUTO_CREATE_ACCOUNT
trim(AUTO_CUST_AC_NO)  AUTO_CUST_AC_NO,         --13   AUTO_CUST_AC_NO
trim(LOCAL_BRANCH)  BRANCH_CODE,         --14   BRANCH_CODE
trim(CAS_CUST)  CAS_CUST,         --15   CAS_CUST
trim(CHARGE_GROUP)  CHARGE_GROUP,         --16   CHARGE_GROUP
trim(CHECKER_DT_STAMP)  CHECKER_DT_STAMP,         --17   CHECKER_DT_STAMP
trim(CHECKER_ID)  CHECKER_ID,         --18   CHECKER_ID
trim(CHK_DIGIT_VALID_REQD)  CHK_DIGIT_VALID_REQD,         --19   CHK_DIGIT_VALID_REQD
trim(CIF_CREATION_DATE)  CIF_CREATION_DATE,         --20   CIF_CREATION_DATE
trim(CIF_STATUS)  CIF_STATUS,         --21   CIF_STATUS
trim(CIF_STATUS_SINCE)  CIF_STATUS_SINCE,         --22   CIF_STATUS_SINCE
trim(CLS_CCY_ALLOWED)  CLS_CCY_ALLOWED,         --23   CLS_CCY_ALLOWED
trim(CLS_PARTICIPANT)  CLS_PARTICIPANT,         --24   CLS_PARTICIPANT
trim(CONSOL_TAX_CERT_REQD)  CONSOL_TAX_CERT_REQD,         --25   CONSOL_TAX_CERT_REQD
'U'  CONVERSION_STATUS_FLAG,         --26   CONVERSION_STATUS_FLAG
trim(COUNTRY)  COUNTRY,         --27   COUNTRY
trim(CREDIT_RATING)  CREDIT_RATING,         --28   CREDIT_RATING
trim(CRM_CUSTOMER)  CRM_CUSTOMER,         --29   CRM_CUSTOMER
trim(CRS_TYPE)  CRS_TYPE,         --30   CRS_TYPE
trim(CUSTOMER_CATEGORY)  CUSTOMER_CATEGORY,         --31   CUSTOMER_CATEGORY
trim(CUSTOMER_NAME1)  CUSTOMER_NAME1,         --32   CUSTOMER_NAME1
NULL  CUSTOMER_NO,         --33   CUSTOMER_NO
trim(CUSTOMER_TYPE)  CUSTOMER_TYPE,         --34   CUSTOMER_TYPE
trim(CUST_CLASSIFICATION)  CUST_CLASSIFICATION,         --35   CUST_CLASSIFICATION
trim(CUST_CLG_GROUP)  CUST_CLG_GROUP,         --36   CUST_CLG_GROUP
null  CUST_UNADVISED,         --37   CUST_UNADVISED
trim(DEBTOR_CATEGORY)  DEBTOR_CATEGORY,         --38   DEBTOR_CATEGORY
trim(DECEASED)  DECEASED,         --39   DECEASED
trim(DEFAULT_MEDIA)  DEFAULT_MEDIA,         --40   DEFAULT_MEDIA
trim(ELCM_CUSTOMER)  ELCM_CUSTOMER,         --41   ELCM_CUSTOMER
null  ERR_MSG,         --42   ERR_MSG
trim(EXPOSURE_CATEGORY)  EXPOSURE_CATEGORY,         --43   EXPOSURE_CATEGORY
trim(EXPOSURE_COUNTRY)  EXPOSURE_COUNTRY,         --44   EXPOSURE_COUNTRY
null  EXT_REF_NO,         --45   EXT_REF_NO
trim(FAX_NUMBER)  FAX_NUMBER,         --46   FAX_NUMBER
trim(FREQUENCY)  FREQUENCY,         --47   FREQUENCY
trim(FROZEN)  FROZEN,         --48   FROZEN
trim(FT_ACCTING_AS_OF)  FT_ACCTING_AS_OF,         --49   FT_ACCTING_AS_OF
trim(FULL_NAME)  FULL_NAME,         --50   FULL_NAME
trim(FX_CLEAN_RISK_LIMIT)  FX_CLEAN_RISK_LIMIT,         --51   FX_CLEAN_RISK_LIMIT
trim(FX_CUST_CLEAN_RISK_LIMIT)  FX_CUST_CLEAN_RISK_LIMIT,         --52   FX_CUST_CLEAN_RISK_LIMIT
trim(FX_NETTING_CUSTOMER)  FX_NETTING_CUSTOMER,         --53   FX_NETTING_CUSTOMER
trim(GENERATE_MT920)  GENERATE_MT920,         --54   GENERATE_MT920
trim(GROUP_CODE)  GROUP_CODE,         --55   GROUP_CODE
trim(HO_AC_NO)  HO_AC_NO,         --56   HO_AC_NO
trim(INDIVIDUAL_TAX_CERT_REQD)  INDIVIDUAL_TAX_CERT_REQD,         --57   INDIVIDUAL_TAX_CERT_REQD
trim(INTRODUCER)  INTRODUCER,         --58   INTRODUCER
trim(INVEST_CUST)  INVEST_CUST,         --59   INVEST_CUST
trim(ISSUER_CUSTOMER)  ISSUER_CUSTOMER,         --60   ISSUER_CUSTOMER
trim(JOINT_VENTURE)  JOINT_VENTURE,         --61   JOINT_VENTURE
trim(KYC_DETAILS)  KYC_DETAILS,         --62   KYC_DETAILS
trim(KYC_REF_NO)  KYC_REF_NO,         --63   KYC_REF_NO
trim(LANGUAGE)  LANGUAGE,         --64   LANGUAGE
trim(LC_COLLATERAL_PCT)  LC_COLLATERAL_PCT,         --65   LC_COLLATERAL_PCT
trim(LIABILITY_NO)  LIABILITY_NO,         --66   LIABILITY_NO
trim(LIAB_BR)  LIAB_BR,         --67   LIAB_BR
trim(LIAB_NODE)  LIAB_NODE,         --68   LIAB_NODE
null  LIAB_UNADVISED,         --69   LIAB_UNADVISED
trim(LIMIT_CCY)  LIMIT_CCY,         --70   LIMIT_CCY
trim(LOCAL_BRANCH)  LOCAL_BRANCH,         --71   LOCAL_BRANCH
trim(LOC_CODE)  LOC_CODE,         --72   LOC_CODE
trim(MAILERS_REQUIRED)  MAILERS_REQUIRED,         --73   MAILERS_REQUIRED
rownum  MAINTENANCE_SEQ_NO,         --74   MAINTENANCE_SEQ_NO
trim(MAKER_DT_STAMP)  MAKER_DT_STAMP,         --75   MAKER_DT_STAMP
trim(MAKER_ID)  MAKER_ID,         --76   MAKER_ID
trim(MFI_CUSTOMER)  MFI_CUSTOMER,         --77   MFI_CUSTOMER
trim(NATIONALITY)  NATIONALITY,         --78   NATIONALITY
trim(OVERALL_LIMIT)  OVERALL_LIMIT,         --79   OVERALL_LIMIT
trim(PAST_DUE_FLAG)  PAST_DUE_FLAG,         --80   PAST_DUE_FLAG
trim(PINCODE)  PINCODE,         --81   PINCODE
trim(PRIVATE_CUSTOMER)  PRIVATE_CUSTOMER,         --82   PRIVATE_CUSTOMER
trim(REVISION_DATE)  REVISION_DATE,         --83   REVISION_DATE
trim(RISK_CATEGORY)  RISK_CATEGORY,         --84   RISK_CATEGORY
trim(RISK_PROFILE)  RISK_PROFILE,         --85   RISK_PROFILE
trim(RM_ID)  RM_ID,         --86   RM_ID
trim(RP_CUSTOMER)  RP_CUSTOMER,         --87   RP_CUSTOMER
trim(SEC_CLEAN_RISK_LIMIT)  SEC_CLEAN_RISK_LIMIT,         --88   SEC_CLEAN_RISK_LIMIT
trim(SEC_CUST_CLEAN_RISK_LIMIT)  SEC_CUST_CLEAN_RISK_LIMIT,         --89   SEC_CUST_CLEAN_RISK_LIMIT
trim(SEC_CUST_PSTL_RISK_LIMIT)  SEC_CUST_PSTL_RISK_LIMIT,         --90   SEC_CUST_PSTL_RISK_LIMIT
trim(SEC_PSTL_RISK_LIMIT)  SEC_PSTL_RISK_LIMIT,         --91   SEC_PSTL_RISK_LIMIT
trim(SHORT_NAME)  SHORT_NAME,         --92   SHORT_NAME
NULL  SHORT_NAME2,         --93   SHORT_NAME2
'DTN_CUST_UPD'  SOURCE_CODE,         --94   SOURCE_CODE
rownum  SOURCE_SEQ_NO,         --95   SOURCE_SEQ_NO
trim(SPECIAL_CUST)  SPECIAL_CUST,         --96   SPECIAL_CUST
trim(SSN)  SSN,         --97   SSN
trim(STAFF)  STAFF,         --98   STAFF
trim(STMT_DAY)  STMT_DAY,         --99   STMT_DAY
trim(SWIFT_CODE)  SWIFT_CODE,         --100   SWIFT_CODE
trim(TAXID_NO)  TAXID_NO,         --101   TAXID_NO
trim(TAX_CNTRY)  TAX_CNTRY,         --102   TAX_CNTRY
trim(TAX_GROUP)  TAX_GROUP,         --103   TAX_GROUP
trim(TRACK_LIMITS)  TRACK_LIMITS,         --104   TRACK_LIMITS
trim(TREASURY_CUSTOMER)  TREASURY_CUSTOMER,         --105   TREASURY_CUSTOMER
trim(UDF_1)  UDF_1,         --106   UDF_1
trim(UDF_2)  UDF_2,         --107   UDF_2
trim(UDF_3)  UDF_3,         --108   UDF_3
trim(UDF_4)  UDF_4,         --109   UDF_4
trim(UDF_5)  UDF_5,         --110   UDF_5
trim(UNIQUE_ID_NAME)  UNIQUE_ID_NAME,         --111   UNIQUE_ID_NAME
trim(UNIQUE_ID_VALUE)  UNIQUE_ID_VALUE,         --112   UNIQUE_ID_VALUE
trim(UTILITY_PROVIDER)  UTILITY_PROVIDER,         --113   UTILITY_PROVIDER
trim(UTILITY_PROVIDER_ID)  UTILITY_PROVIDER_ID,         --114   UTILITY_PROVIDER_ID
trim(UTILITY_PROVIDER_TYPE)  UTILITY_PROVIDER_TYPE,         --115   UTILITY_PROVIDER_TYPE
trim(VRTL_CUSTOMER_ID)  VRTL_CUSTOMER_ID,         --116   VRTL_CUSTOMER_ID
trim(WHEREABOUTS_UNKNOWN)  WHEREABOUTS_UNKNOWN,         --117   WHEREABOUTS_UNKNOWN
trim(WHT_PCT)  WHT_PCT,         --118   WHT_PCT
trim(WITHHOLDING_TAX)  WITHHOLDING_TAX          --119   WITHHOLDING_TAX
from  STTM_CUSTOMER WHERE CUSTOMER_NO IN 
('0212625','0212625','0212625','0212625','0212625','0212649','0212649','0212649','0212649','0212649',
'0212651','0212651','0212651','0212651','0212651','0212650','0212650','0212650','0212650','0212650',
'0212627','0212627','0212627','0212627','0212637','0212628','0212628','0212628','0212622','0212636',
'0212635','0212635','0212635','0212640','0212640','0212641','0212641','0212644','0212644','0212643',
'0212647','0212647','0212648','0212642','0212646','0212645','0212626','0212639','0212639','0212629',
'0212629','0212629','0212630','0212630','0212634','0212634','0212634','0212632','0212633','0212633','0212633');








insert into STTM_UPLOAD_CUST_CORPORATE (
AMOUNTS_CCY,         --1   AMOUNTS_CCY
BRANCH_CODE,         --2   BRANCH_CODE
BUSINESS_DESCRIPTION,         --3   BUSINESS_DESCRIPTION
CAPITAL,         --4   CAPITAL
CONVERSION_STATUS_FLAG,         --5   CONVERSION_STATUS_FLAG
CORPORATE_NAME,         --6   CORPORATE_NAME
CUSTOMER_NO,         --7   CUSTOMER_NO
C_NATIONAL_ID,         --8   C_NATIONAL_ID
ERR_MSG,         --9   ERR_MSG
INCORP_COUNTRY,         --10   INCORP_COUNTRY
INCORP_DATE,         --11   INCORP_DATE
MAINTENANCE_SEQ_NO,         --12   MAINTENANCE_SEQ_NO
NETWORTH,         --13   NETWORTH
OWNERSHIP_TYPE,         --14   OWNERSHIP_TYPE
PREF_CONTACT_DT,         --15   PREF_CONTACT_DT
PREF_CONTACT_TIME,         --16   PREF_CONTACT_TIME
R_ADDRESS1,         --17   R_ADDRESS1
R_ADDRESS2,         --18   R_ADDRESS2
R_ADDRESS3,         --19   R_ADDRESS3
R_ADDRESS4,         --20   R_ADDRESS4
R_COUNTRY,         --21   R_COUNTRY
R_PINCODE,         --22   R_PINCODE
SOURCE_CODE,         --23   SOURCE_CODE
SOURCE_SEQ_NO)         --24   SOURCE_SEQ_NO


select 
trim(A.AMOUNTS_CCY)  AMOUNTS_CCY,         --1   AMOUNTS_CCY
trim(LOCAL_BRANCH) BRANCH_CODE,         --2   BRANCH_CODE
trim(A.BUSINESS_DESCRIPTION)  BUSINESS_DESCRIPTION,         --3   BUSINESS_DESCRIPTION
trim(A.CAPITAL)  CAPITAL,         --4   CAPITAL
'U'  CONVERSION_STATUS_FLAG,         --5   CONVERSION_STATUS_FLAG
trim(A.CORPORATE_NAME)  CORPORATE_NAME,         --6   CORPORATE_NAME
trim(A.CUSTOMER_NO)  CUSTOMER_NO,         --7   CUSTOMER_NO
trim(A.C_NATIONAL_ID)  C_NATIONAL_ID,         --8   C_NATIONAL_ID
null  ERR_MSG,         --9   ERR_MSG
trim(A.INCORP_COUNTRY)  INCORP_COUNTRY,         --10   INCORP_COUNTRY
trim(A.INCORP_DATE)  INCORP_DATE,         --11   INCORP_DATE
null  MAINTENANCE_SEQ_NO,         --12   MAINTENANCE_SEQ_NO
trim(A.NETWORTH)  NETWORTH,         --13   NETWORTH
trim(A.OWNERSHIP_TYPE)  OWNERSHIP_TYPE,         --14   OWNERSHIP_TYPE
trim(A.PREF_CONTACT_DT)  PREF_CONTACT_DT,         --15   PREF_CONTACT_DT
trim(A.PREF_CONTACT_TIME)  PREF_CONTACT_TIME,         --16   PREF_CONTACT_TIME
trim(A.R_ADDRESS1)  R_ADDRESS1,         --17   R_ADDRESS1
trim(A.R_ADDRESS2)  R_ADDRESS2,         --18   R_ADDRESS2
trim(A.R_ADDRESS3)  R_ADDRESS3,         --19   R_ADDRESS3
trim(A.R_ADDRESS4)  R_ADDRESS4,         --20   R_ADDRESS4
trim(A.R_COUNTRY)  R_COUNTRY,         --21   R_COUNTRY
trim(A.R_PINCODE)  R_PINCODE,         --22   R_PINCODE
'DTN_CUST_UPD'  SOURCE_CODE,         --23   SOURCE_CODE
B.SOURCE_SEQ_NO  SOURCE_SEQ_NO          --24   SOURCE_SEQ_NO
from  STTM_CUST_CORPORATE A,
STTM_UPLOAD_CUSTOMER B
WHERE 1=1
AND A.CUSTOMER_NO = B.CUSTOMER_NO;


