DROP SEQUENCE FF_SEQ_CLIENT_FLEX;

CREATE SEQUENCE FF_SEQ_CLIENT_FLEX INCREMENT BY 1 START WITH 12000001 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

TRUNCATE TABLE STTM_UPLOAD_CUSTOMER;

INSERT INTO STTM_UPLOAD_CUSTOMER (
SOURCE_CODE,
MAINTENANCE_SEQ_NO,
CUSTOMER_NO,
CUSTOMER_TYPE,
CUSTOMER_NAME1,
ADDRESS_LINE1,
ADDRESS_LINE3,
ADDRESS_LINE2,
ADDRESS_LINE4,
COUNTRY,
SHORT_NAME,
NATIONALITY,
LANGUAGE,
EXPOSURE_COUNTRY,
LOCAL_BRANCH,
LIABILITY_NO,
UNIQUE_ID_NAME,
UNIQUE_ID_VALUE,
FROZEN,
DECEASED,
WHEREABOUTS_UNKNOWN,
CUSTOMER_CATEGORY,
HO_AC_NO,
FX_CUST_CLEAN_RISK_LIMIT,
OVERALL_LIMIT,
FX_CLEAN_RISK_LIMIT,
CREDIT_RATING,
REVISION_DATE,
LIMIT_CCY,
CAS_CUST,
CONVERSION_STATUS_FLAG,
ERR_MSG,
SEC_CUST_CLEAN_RISK_LIMIT,
SEC_CLEAN_RISK_LIMIT,
SEC_CUST_PSTL_RISK_LIMIT,
SEC_PSTL_RISK_LIMIT,
SWIFT_CODE,
LIAB_BR,
LIAB_NODE,
PAST_DUE_FLAG,
DEFAULT_MEDIA,
LOC_CODE,
SHORT_NAME2,
SSN,
ACTION_CODE,
UTILITY_PROVIDER,
UTILITY_PROVIDER_ID,
RISK_PROFILE,
DEBTOR_CATEGORY,
UDF_1,
UDF_2,
UDF_3,
UDF_4,
UDF_5,
MAILERS_REQUIRED,
AML_CUSTOMER_GRP,
AML_REQUIRED,
GROUP_CODE,
EXPOSURE_CATEGORY,
CUST_CLASSIFICATION,
CIF_STATUS,
CIF_STATUS_SINCE,
INTRODUCER,
FT_ACCTING_AS_OF,
CUST_UNADVISED,
LIAB_UNADVISED,
TAX_GROUP,
CONSOL_TAX_CERT_REQD,
INDIVIDUAL_TAX_CERT_REQD,
FX_NETTING_CUSTOMER,
CLS_PARTICIPANT,
CLS_CCY_ALLOWED,
RISK_CATEGORY,
FAX_NUMBER,
EXT_REF_NO,
CRM_CUSTOMER,
ISSUER_CUSTOMER,
TREASURY_CUSTOMER,
CHARGE_GROUP,
FULL_NAME,
MAKER_ID,
MAKER_DT_STAMP,
CHECKER_ID,
CHECKER_DT_STAMP,
CUST_CLG_GROUP,
CHK_DIGIT_VALID_REQD,
ALG_ID,
SOURCE_SEQ_NO,
BRANCH_CODE,
STAFF,
KYC_REF_NO,
KYC_DETAILS,
LC_COLLATERAL_PCT,
AR_AP_TRACKING,
AUTO_CREATE_ACCOUNT,
AUTO_CUST_AC_NO,
TRACK_LIMITS,
TAXID_NO,
WITHHOLDING_TAX,
SPECIAL_CUST,
CRS_TYPE,
TAX_CNTRY,------
WHT_PCT,
RP_CUSTOMER,
GENERATE_MT920,
PRIVATE_CUSTOMER,
RM_ID,
PINCODE,
AUTOGEN_STMTPLAN,
FREQUENCY,
STMT_DAY,
INVEST_CUST,
ALLOW_VRTL_ACCNTS,
VRTL_CUSTOMER_ID,
ELCM_CUSTOMER,
CIF_CREATION_DATE,
MFI_CUSTOMER,
JOINT_VENTURE,
UTILITY_PROVIDER_TYPE

)
Select 'AMPL_CUST_UPD' SOURCE_CODE,
ff_seq_client_flex.nextval MAINTENANCE_SEQ_NO,
NULL CUSTOMER_NO,
customer_type(cli) CUSTOMER_TYPE,
C.nom CUSTOMER_NAME1     ,
ADDRESS_LINE1(cli) ADDRESS_LINE1     ,
ADDRESS_LINE2(cli) ADDRESS_LINE2,
ADDRESS_LINE3(cli) ADDRESS_LINE3, 
ADDRESS_LINE3(cli) ADDRESS_LINE4,  
(select nvl(max(rtrim(ltrim(lib2))),'GH')
from bknom WHERE ctab='040' and cacc=(
select max(cpay)
from bkadcli where cli=c.cli and ADDRESS_LINE1(c.cli)=adr1) ) COUNTRY,
c.cli SHORT_NAME ,
(select rtrim(ltrim(max(lib2))) from bknom where ctab='040' and cacc=c.nat) NATIONALITY, FF_LANG_CLI_TIERS_ISO2(c.lang,'') LANGUAGE, 'GH' EXPOSURE_COUNTRY, FF_BRANCH_CODE(c.age) LOCAL_BRANCH, NULL LIABILITY_NO,  FF_UNIQUE_ID_NAME(rtrim(ltrim(c.tid))) UNIQUE_ID_NAME, 
c.nid UNIQUE_ID_VALUE, FF_FROZEN_DCD(cli,'10') FROZEN,
FF_FROZEN_DCD(cli,'08') DECEASED, 
FF_WHEREABOUTS_UNKNOWN(cli,'40') WHEREABOUTS_UNKNOWN,
--(Select customer_category from customer_cat_mapping cu where rtrim(ltrim(cu.catn))=rtrim(ltrim(c.catn))   ) 
FF_CUSTOMER_CATEGORY(c.cli) CUSTOMER_CATEGORY, 
NULL HO_AC_NO, 
NULL FX_CUST_CLEAN_RISK_LIMIT, 
NULL OVERALL_LIMIT, 
NULL FX_CLEAN_RISK_LIMIT, 
NULL CREDIT_RATING, 
NULL REVISION_DATE, 
'GHS' LIMIT_CCY,
NULL CAS_CUST,
'U'  CONVERSION_STATUS_FLAG, 
NULL ERR_MSG,
NULL SEC_CUST_CLEAN_RISK_LIMIT,
NULL SEC_CLEAN_RISK_LIMIT,
NULL SEC_CUST_PSTL_RISK_LIMIT,
NULL SEC_PSTL_RISK_LIMIT,
(case when customer_type(cli)='B' then FF_BANK_SWIFT_CODE(c.cli) else NULL end) SWIFT_CODE, 
FF_BRANCH_CODE(c.age) LIAB_BR,
NULL LIAB_NODE, ---(SELECT SYS_CONTEXT('USERENV','SERVER_HOST') FROM dual)
'' PAST_DUE_FLAG,
'MAIL' DEFAULT_MEDIA,
FF_LOCATION_CODE(c.regn) LOC_CODE,
substr(c.nom,1,20) SHORT_NAME2, (case when c.nis ='                    ' then null else substr(NVL(c.nis,NULL),1,11) end) SSN ,'NEW' ACTION_CODE,
NULL UTILITY_PROVIDER  ,
NULL UTILITY_PROVIDER_ID  ,
NULL RISK_PROFILE,
NULL DEBTOR_CATEGORY   ,
NULL UDF_1 ,
NULL UDF_2 ,
NULL UDF_3 ,
NULL UDF_4 ,
NULL UDF_5 ,
'N' MAILERS_REQUIRED,
NULL AML_CUSTOMER_GRP,
'N' AML_REQUIRED, ---DEJI VALIDATION 18112011
NULL GROUP_CODE,
NULL EXPOSURE_CATEGORY,
NULL CUST_CLASSIFICATION      ,
NULL CIF_STATUS ,
NULL CIF_STATUS_SINCE  ,
NULL INTRODUCER ,
'N' FT_ACCTING_AS_OF  , ---DEJI VALIDATION 18112011
NULL CUST_UNADVISED    ,
NULL LIAB_UNADVISED    ,
NULL TAX_GROUP  ,
'N' CONSOL_TAX_CERT_REQD     ,
'Y' INDIVIDUAL_TAX_CERT_REQD ,
NULL FX_NETTING_CUSTOMER      ,
'N' CLS_PARTICIPANT   ,
NULL CLS_CCY_ALLOWED   , -- DEJI VALIDATION 18112011
c.rrc RISK_CATEGORY     ,
(
select nvl(num,'') fax  from bktelcli where typ in (
select  cacc from bknom where ctab='182' and mnt2='2') and cli=c.cli)
FAX_NUMBER ,
c.cli EXT_REF_NO,
'N' CRM_CUSTOMER      ,
'N' ISSUER_CUSTOMER   ,
NULL TREASURY_CUSTOMER ,
NULL CHARGE_GROUP      ,
c.nomrest FULL_NAME  ,
'MIG_USER1' MAKER_ID  ,
sysdate MAKER_DT_STAMP    ,
'MIG_USER2' CHECKER_ID ,
sysdate CHECKER_DT_STAMP  ,
NULL CUST_CLG_GROUP ,
'N' CHK_DIGIT_VALID_REQD     ,
NULL ALG_ID     ,
ff_seq_client_flex.nextval  SOURCE_SEQ_NO,
FF_BRANCH_CODE(c.age) BRANCH_CODE,
FF_STAFF_BQE(cli) STAFF,
NULL KYC_REF_NO,
'N' KYC_DETAIL,
NULL LC_COLLATERAL_PCT,
'N' AR_AP_TRACKING,
'N' AUTO_CREATE_ACCOUNT,
NULL AUTO_CUST_AC_NO,
'Y' TRACK_LIMITS,
c.nidf TAXID_NO,
NULL WITHHOLDING_TAX,   --- DEJI VALIDATION 18112011
'N' SPECIAL_CUST,
NULL CRS_TYPE,  --DEJI VALIDATION 18112011
'GH' TAX_CNTRY,
NULL WHT_PCT,  --DEJI VALIDATION 18112011
NULL RP_CUSTOMER,
NULL GENERATE_MT920,
NULL PRIVATE_CUSTOMER,
NULL RM_ID,
NULL PINCODE,
NULL AUTOGEN_STMTPLAN,
NULL FREQUENCY,
NULL STMT_DAY,
NULL INVEST_CUST,
NULL ALLOW_VRTL_ACCNTS,
NULL VRTL_CUSTOMER_ID,
NULL ELCM_CUSTOMER,
c.dou CIF_CREATION_DATE,
NULL MFI_CUSTOMER,
NULL JOINT_VENTURE,
NULL UTILITY_PROVIDER_TYPE --DEJI VALIDATION 18112011

From bkcli c ; 

commit;
------- FIN MASTER UPLOAD TABLE----

---------DOMESTIC---------
Truncate Table STTM_UPLOAD_CUST_DOMESTIC;
Insert into STTM_UPLOAD_CUST_DOMESTIC 
select 
NULL CUSTOMER_NO,
NULL EDUCATIONAL_STATUS,
--NULL MARITAL_STATUS,
CASE c.sit 
	WHEN	'A'		THEN NULL    --- OTHER
    WHEN    'C'		THEN 'S'	-- SINGLE
    WHEN    'D'		THEN 'D'	-- DIVORCED
    WHEN    'M'		THEN 'M'	-- MARRIED
    WHEN    'S'		THEN 'S'	-- SEPARATED
    WHEN    'V'		THEN 'E'	-- WIDOW / WIDOWER
    WHEN    'X'		THEN NULL	-- CO-HABITATION
	ELSE NULL
END  MARITAL_STATUS, -- dsam added 20220516
    
FF_SPOUSE_NAME_COJ(conj,tconj) SPOUSE_NAME,
NULL SPOUSE_EMP_STATUS,
nbenf DEPENDENT_CHILDREN,
null DEPENDENT_OTHERS,
null ACCOMODATION,   
'U' CONVERSION_STATUS_FLAG,
NULL ERR_MSG,
s.MAINTENANCE_SEQ_NO MAINTENANCE_SEQ_NO,
c.nmer MOTHER_MAIDEN_NAME
from bkcli c, STTM_UPLOAD_CUSTOMER s
where c.cli= s.ext_ref_no and c.tconj in ('T','C');

commit;
----DOMESTIC-------------

--Personnal Insertion
---------------------

---------------
Truncate table STTM_UPLOAD_PERSONAL_JOINT;
Insert into STTM_UPLOAD_PERSONAL_JOINT
Select 
FF_CUSTOMER_PREFIX(c.lib,'') CUSTOMER_PREFIX,
c.nom FIRST_NAME, 
c.midname MIDDLE_NAME,
c.pre LAST_NAME,
c.dna DATE_OF_BIRTH, 
c.sext SEX,       
FF_P_NATIONAL_ID(coj.cli, '00001')PASSPORT_NO,
FF_PPT_ISS_DATE(coj.cli, '00002') PPT_ISS_DATE,
FF_PPT_EXP_DATE(coj.cli, '00002') PPT_EXP_DATE ,
FF_GE_ADDRESS_LINE1_COJ(coj.cli,coj.tco) D_ADDRESS1 ,
FF_GE_ADDRESS_LINE2_COJ(coj.cli,coj.tco) D_ADDRESS2 ,
FF_GE_ADDRESS_LINE3_COJ(coj.cli,coj.tco) D_ADDRESS3 ,
FF_E_TELEPHONE_CLI_TIERS(coj.cli,coj.tco) TELEPHONE,
FF_EMAIL_CLIENT_TIERS(coj.cli,coj.tco)   E_MAIL,   
s.SSN    SSN  ,
s.DECEASED DECEASED,
-- '' RESIDENT_STATUS, 
CASE c.resd
	WHEN '001'	THEN 'R'
	WHEN '002'	THEN 'N'
	ELSE NULL
END RESIDENT_STATUS, -- dsam 20220516
NULL CUSTOMER_NO   ,  
coj.ord RECORD_NO,
s.CONVERSION_STATUS_FLAG CONVERSION_STATUS_FLAG,
s.ERR_MSG  ERR_MSG,
to_number(s.MAINTENANCE_SEQ_NO)     MAINTENANCE_SEQ_NO,
s.SOURCE_SEQ_NO   SOURCE_SEQ_NO,
s.BRANCH_CODE   BRANCH_CODE,
s.SOURCE_CODE   SOURCE_CODE   
FROM Bkcoj coj, STTM_UPLOAD_CUSTOMER s, BKCLI c where c.cli= s.ext_ref_no and c.cli=coj.clip 
and coj.tco='T'
and c.lib<>31;
-----personn joint
------
commit;

Truncate table STTM_UPLOAD_CUST_PERSONAL;
Insert into STTM_UPLOAD_CUST_PERSONAL
(CUSTOMER_PREFIX,
FIRST_NAME,
MIDDLE_NAME,
LAST_NAME,
DATE_OF_BIRTH,
LEGAL_GUARDIAN,
MINOR,
SEX,
P_NATIONAL_ID,
PASSPORT_NO,
PPT_ISS_DATE,
PPT_EXP_DATE,
D_ADDRESS1,
D_ADDRESS2,
D_ADDRESS3,
TELEPHONE,
FAX,
E_MAIL,
P_ADDRESS1,
P_ADDRESS3,
P_ADDRESS2,
CUSTOMER_NO,
D_COUNTRY,
P_COUNTRY,
RESIDENT_STATUS,
CONVERSION_STATUS_FLAG,
ERR_MSG,
MAINTENANCE_SEQ_NO,
CUSTOMER_PREFIX1,
CUSTOMER_PREFIX2,
SOURCE_SEQ_NO,
BRANCH_CODE,
SOURCE_CODE,
AGE_PROOF_SUBMITTED,
P_ADDRESS4,
D_ADDRESS4,
PLACE_OF_BIRTH,
BIRTH_COUNTRY,
TEL_ISD_NO,
MOB_ISD_NO,
FAX_ISD_NO,
US_RES_STATUS,
PA_ISSUED,
PA_HOLDER_NAME,
PA_HOLDER_NATIONALTY,
PA_HOLDER_ADDR,
PA_HOLDER_ADDR_COUNTRY,
PA_HOLDER_TEL_ISD,
PA_HOLDER_TEL_NO,
VST_US_PREV,
MOBILE_NUMBER,
CUST_COMM_MODE,
HOME_TEL_NO,
HOME_TEL_ISD,
P_PINCODE,
PREF_CONTACT_DT,
PREF_CONTACT_TIME,
D_PINCODE,
MOTHER_MAIDEN_NAME)

Select  
FF_CUSTOMER_PREFIX(c.lib,'') CUSTOMER_PREFIX,
c.pre FIRST_NAME, --20012022
c.midname MIDDLE_NAME,
c.nom LAST_NAME, --20012022
c.dna DATE_OF_BIRTH,
FF_LEGAL_GUARDIAN(c.cli) LEGAL_GUARDIAN ,
FF_MINOR(c.cli) MINOR, 
c.sext SEX, 
FF_P_NATIONAL_ID(c.cli, '00001') P_NATIONAL_ID,
FF_P_NATIONAL_ID(c.cli, '00002')PASSPORT_NO,
FF_PPT_ISS_DATE(c.cli, '00002') PPT_ISS_DATE,
FF_PPT_EXP_DATE(c.cli, '00002') PPT_EXP_DATE ,
FF_GE_ADDRESS_LINE1(c.cli) D_ADDRESS1 ,
FF_GE_ADDRESS_LINE2(c.cli) D_ADDRESS2 ,
FF_GE_ADDRESS_LINE3(c.cli) D_ADDRESS3 ,
FF_E_TELEPHONE_CLI(c.cli) TELEPHONE,
FF_E_FAX_CLI(c.cli) FAX ,
--FF_EM_ADDRESS_LINE1(c.cli)   E_MAIL,
FF_EM_EMAIL(c.cli)   E_MAIL, -- dsam 20220520
FF_P_ADDRESS_LINE1(c.cli) P_ADDRESS1, 
FF_P_ADDRESS_LINE3(c.cli) P_ADDRESS3, 
FF_P_ADDRESS_LINE2(c.cli) P_ADDRESS2 ,
NULL CUSTOMER_NO,
NULL D_COUNTRY,
NVL(( select rtrim(ltrim(max(lib2))) 
        from bknom bn, bkadcli ba
        where ctab='040' and bn.cacc= ba.cpay and ba.cli = c.cli),'GH') P_COUNTRY,  -- dsam: mapped to bkadcli.cpay

--NULL RESIDENT_STATUS, 
CASE c.resd
	WHEN '001'	THEN 'R'
	WHEN '002'	THEN 'N'
	ELSE NULL
END RESIDENT_STATUS, -- dsam 20220516

s.CONVERSION_STATUS_FLAG CONVERSION_STATUS_FLAG,
s.ERR_MSG ERR_MSG,
s.MAINTENANCE_SEQ_NO MAINTENANCE_SEQ_NO,
NULL CUSTOMER_PREFIX1,
NULL CUSTOMER_PREFIX2,
s.SOURCE_SEQ_NO SOURCE_SEQ_NO,
s.BRANCH_CODE BRANCH_CODE,
s.SOURCE_CODE SOURCE_CODE,
NULL AGE_PROOF_SUBMITTED,
NULL P_ADDRESS4,
NULL D_ADDRESS4 ,
c.viln PLACE_OF_BIRTH,
FF_BIRTH_COUNTRY_CLI_TIERS(c.cli,'C')  BIRTH_COUNTRY, -- c.payn 17012022
FF_E_TELEPHONE_CLI_ISD(c.cli) TEL_ISD_NO ,
FF_E_MOBILE_CLI_ISD(c.cli) MOB_ISD_NO ,
FF_E_FAX_CLI_ISD(c.cli) FAX_ISD_NO ,
'N' US_RES_STATUS,
NULL PA_ISSUED,
NULL PA_HOLDER_NAME ,
NULL PA_HOLDER_NATIONALTY ,
NULL PA_HOLDER_ADDR,
NULL PA_HOLDER_ADDR_COUNTRY,
NULL PA_HOLDER_TEL_ISD,
NULL PA_HOLDER_TEL_NO ,
'N' VST_US_PREV ,
FF_E_MOBILE_CLI(c.cli) MOBILE_NUMBER ,
'M' CUST_COMM_MODE ,
'' HOME_TEL_NO,
'' HOME_TEL_ISD,
'' P_PINCODE,
'' PREF_CONTACT_DT,
'' PREF_CONTACT_TIME,
'' D_PINCODE,
c.nmer MOTHER_MAIDEN_NAME --20012022
FROM Bkcli c, STTM_UPLOAD_CUSTOMER s where c.cli= s.ext_ref_no
and s.customer_type='I' ;--and not exists (SELECT * FROM bkprfcli pf where pf.cli=c.cli and emp <>' ');

commit;
--select * from customer_prefix_mapping
--select distinct FF_CUSTOMER_PREFIX(lib,'') from bkcli

------CORPORATE INSERTION------
Truncate table STTM_UPLOAD_CUST_CORPORATE;
Insert into STTM_UPLOAD_CUST_CORPORATE
(CUSTOMER_NO,
CORPORATE_NAME,
C_NATIONAL_ID,
R_ADDRESS1,
R_ADDRESS2,
R_ADDRESS3,
INCORP_DATE,
CAPITAL,
NETWORTH,
BUSINESS_DESCRIPTION,
INCORP_COUNTRY,
R_COUNTRY,
AMOUNTS_CCY,
CONVERSION_STATUS_FLAG,
ERR_MSG,
MAINTENANCE_SEQ_NO,
SOURCE_SEQ_NO,
BRANCH_CODE,
SOURCE_CODE,
R_ADDRESS4,
R_PINCODE,
PREF_CONTACT_DT,
PREF_CONTACT_TIME,
OWNERSHIP_TYPE)


select NULL  CUSTOMER_NO,     
c.nomrest CORPORATE_NAME,  --20012022
c.nrc C_NATIONAL_ID,   
FF_ADDRESS_LINE1(cli) R_ADDRESS1,      
FF_ADDRESS_LINE2(cli) R_ADDRESS2,      
FF_ADDRESS_LINE3(cli) R_ADDRESS3 ,     
c.dsitj INCORP_DATE,     
NULL CAPITAL , 
NULL NETWORTH ,
FF_BUSINESS_DESCRIPTION(c.sec) BUSINESS_DESCRIPTION   ,
'GH' INCORP_COUNTRY  ,
NULL R_COUNTRY ,
NULL AMOUNTS_CCY   ,  
s.conversion_status_flag CONVERSION_STATUS_FLAG ,
s.err_msg ERR_MSG  ,
s.maintenance_seq_no MAINTENANCE_SEQ_NO     ,
s.maintenance_seq_no SOURCE_SEQ_NO   ,
s.BRANCH_CODE BRANCH_CODE   ,  --bank mapping
s.SOURCE_CODE SOURCE_CODE   ,  
NULL R_ADDRESS4   ,
'' R_PINCODE,
'' PREF_CONTACT_DT,
'' PREF_CONTACT_TIME,
'' OWNERSHIP_TYPE
FROM Bkcli c, STTM_UPLOAD_CUSTOMER s where c.cli= s.ext_ref_no
and s.customer_type in ('C','B');


commit;

------------------------------
------------------------------ Table z_udf
/*
create table z_udf(
customer_no                    varchar(100),
new_cust_no                    varchar(100),
means_of_identification        varchar(100),
identification_id_number       varchar(100),
issue_date                     date,
expiry                         date);
*/

Truncate table z_udf;
insert into z_udf 
select st.ext_ref_no customer, '' new_cust_no, MEANS_OF_IDENTIFICATION(rtrim(ltrim(tid))),nid identification_id_number, bk.did issue_date,bk.vid expiry

from bkcli bk, STTM_UPLOAD_CUSTOMER st
where bk.cli=st.ext_ref_no; 
commit;

------------------------------------
------------------------------------------------

/* 
-----SHAREHOLDERS -----
Truncate table STTM_UPLOAD_CUST_SHAREHOLDER ;
Insert into STTM_UPLOAD_CUST_SHAREHOLDER
Select 
NULL CUSTOMER_NO ,
 to_char((rtrim(ltrim(C.cact)))) SHAREHOLDER_ID, 
C.pcap PERCENTAGE_HOLDING,    
'U' CONVERSION_STATUS_FLAG,
NULL ERR_MSG ,
s.MAINTENANCE_SEQ_NO     MAINTENANCE_SEQ_NO,
s.SOURCE_SEQ_NO  SOURCE_SEQ_NO,
s.BRANCH_CODE    BRANCH_CODE,
s.SOURCE_CODE  SOURCE_CODE  
From BKACTCLI C,  STTM_UPLOAD_CUSTOMER s , BKCLI A
Where c.cli=a.cli and a.cli=s.ext_ref_no;

commit;
----- FIN SHAREHOLDERS ----


-----DIRECTORS ------
Truncate Table STTM_UPLOAD_CORP_DIRECTORS;
Insert into STTM_UPLOAD_CORP_DIRECTORS
(
CUSTOMER_NO,
DIRECTOR_NAME,
CONVERSION_STATUS_FLAG,
ERR_MSG,
MAINTENANCE_SEQ_NO,
SOURCE_SEQ_NO,
BRANCH_CODE,
SOURCE_CODE,
ADDRESS_LINE1,
ADDRESS_LINE2,
ADDRESS_LINE3,
ADDRESS_LINE4,
P_ADDRESS1,
P_ADDRESS2,
P_ADDRESS3,
P_ADDRESS4,
P_COUNTRY,
TELEPHONE,
TAX_ID,
MOBILE_NUMBER,
E_MAIL,
SLNO,
TEL_ISD_NO,
MOB_ISD_NO,
ADDR_COUNTRY,
NATIONALITY,
US_RES_STATUS,
PCT_HOLDING,
TAX_CNTRY,
DATE_OF_BIRTH,
PLACE_OF_BIRTH,
BIRTH_COUNTRY,
OWNERSHIP_TYPE,
HOME_TEL_NO,
HOME_TEL_ISD,
P_PINCODE,
PINCODE)

Select 
NULL CUSTOMER_NO     ,
FF_SPOUSE_NAME_COJ(d.cdir,d.typ) DIRECTOR_NAME   ,
S.CONVERSION_STATUS_FLAG CONVERSION_STATUS_FLAG,
S.ERR_MSG  ERR_MSG,
s.MAINTENANCE_SEQ_NO   MAINTENANCE_SEQ_NO  ,
s.SOURCE_SEQ_NO   SOURCE_SEQ_NO,
s.BRANCH_CODE     BRANCH_CODE,
s.SOURCE_CODE     SOURCE_CODE,
FF_GE_ADDRESS_LINE1_COJ(d.cdir,d.typ) ADDRESS_LINE1,
FF_GE_ADDRESS_LINE1_COJ(d.cdir,d.typ) ADDRESS_LINE2,
FF_GE_ADDRESS_LINE1_COJ(d.cdir,d.typ) ADDRESS_LINE3 ,
NULL ADDRESS_LINE4,
FF_P_ADDRESS_LINE1_CT(d.cdir,d.typ) P_ADDRESS1 ,
FF_P_ADDRESS_LINE2_CT(d.cdir,d.typ) P_ADDRESS2,
FF_P_ADDRESS_LINE3_CT(d.cdir,d.typ) P_ADDRESS3,
NULL P_ADDRESS4 ,
--FF_BIRTH_COUNTRY_CLI_TIERS(d.cdir,d.typ) P_COUNTRY, correct 18012022
NVL(( select rtrim(ltrim(max(lib2))) 
        from bknom
        where ctab='040' and cacc= d.nat),'GH') P_COUNTRY,
FF_E_TELEPHONE_CLI_TIERS(d.cdir,d.typ) TELEPHONE,
s.TAXID_NO TAX_ID,
FF_E_MOBILE_CLI_TIERS(d.cdir,d.typ) MOBILE_NUMBER,
FF_EMAIL_CLIENT_TIERS(d.cdir,d.typ) E_MAIL, 
d.ord SLNO ,
FF_E_TELEPHONE_CLI_TIERS_ISD(d.cdir,d.typ) TEL_ISD_NO ,
FF_E_MOBILE_CLI_TIERS_ISD(d.cdir,d.typ) MOB_ISD_NO,
null ADDR_COUNTRY ,
FF_NAT_CLI_TIERS(d.nat,d.typ) NATIONALITY,
'N' US_RES_STATUS,
NULL PCT_HOLDING,
NULL TAX_CNTRY,
FF_DNA_COJ(d.cdir,d.typ) DATE_OF_BIRTH,
FF_PLACE_OF_BIRTH_CLI_TIERS(d.cdir,d.typ) PLACE_OF_BIRTH,
FF_BIRTH_COUNTRY_CLI_TIERS(d.cdir,d.typ) BIRTH_COUNTRY,
null OWNERSHIP_TYPE,
'' HOME_TEL_NO,
'' HOME_TEL_ISD,
'' P_PINCODE,
'' PINCODE

From  bkdircli d,  STTM_UPLOAD_CUSTOMER s , BKCLI A
Where d.cli=a.cli and a.cli=s.ext_ref_no and s.customer_type <> 'I';

commit;
--select * from bkdircli
---------------------
---- Insertion of professionnals

Truncate table STTM_UPLOAD_CUST_PROFESSIONAL;
--select * from STTM_UPLOAD_CUST_PROFESSIONALF;
Insert into STTM_UPLOAD_CUST_PROFESSIONAL
(CUSTOMER_NO,
EMPLOYMENT_STATUS,
EMPLOYMENT_TENURE,
RETIREMENT_AGE,
PREV_DESIGNATION,
PREV_EMPLOYER,
DESIGNATION,
EMPLOYER,
E_ADDRESS1,
E_ADDRESS2,
E_ADDRESS3,
E_TELEPHONE,
E_TELEX,
E_FAX,
E_EMAIL,
SALARY,
OTHER_EXPENSES,
OTHER_INCOME,
RENT,
INSURANCE,
LOAN_PAYMENT,
HOUSE_VALUE,
CREDIT_CARDS,
E_COUNTRY,
CCY_PERS_INCEXP,
CONVERSION_STATUS_FLAG,
ERR_MSG,
MAINTENANCE_SEQ_NO,
SOURCE_SEQ_NO,
BRANCH_CODE,
SOURCE_CODE,
E_ADDRESS4,
SALARY_FREQ,
PINCODE
)

Select
NULL CUSTOMER_NO     ,
NULL EMPLOYMENT_STATUS, --bank      
NULL EMPLOYMENT_TENURE ,      
60   RETIREMENT_AGE,  
NULL PREV_DESIGNATION,
NULL PREV_EMPLOYER   ,
NULL DESIGNATION     , --- a revoir
FF_EMPLOYER(c.cli) EMPLOYER ,
ff_e_address1(ff_employer(c.cli)) E_ADDRESS1 ,     
ff_e_address2(ff_employer(c.cli)) E_ADDRESS2 ,     
ff_e_address3(ff_employer(c.cli)) E_ADDRESS3 ,     
ff_e_telephone(ff_employer(c.cli)) E_TELEPHONE,     
null E_TELEX,-- pas defini  
null E_FAX   , -- pas defini 
ff_e_telephone(ff_employer(c.cli)) E_EMAIL , 
NULL SALARY ,  
NULL OTHER_EXPENSES  ,
NULL OTHER_INCOME  ,  
NULL RENT     ,
NULL INSURANCE ,
NULL LOAN_PAYMENT ,   
NULL HOUSE_VALUE  ,   
NULL CREDIT_CARDS    ,
FF_E_COUNTRY(ff_employer(c.cli)) E_COUNTRY,
'GHS' CCY_PERS_INCEXP ,
s.CONVERSION_STATUS_FLAG CONVERSION_STATUS_FLAG ,
s.err_msg ERR_MSG  ,
s.maintenance_seq_no MAINTENANCE_SEQ_NO ,    
s.source_seq_no SOURCE_SEQ_NO   ,
s.branch_code BRANCH_CODE     ,
s.source_code SOURCE_CODE  ,   
'' E_ADDRESS4,
'' SALARY_FREQ,
'' PINCODE

FROM Bkcli c, STTM_UPLOAD_CUSTOMER s where c.cli= s.ext_ref_no
and s.customer_type='I' and exists (SELECT * FROM bkprfcli pf where pf.cli=c.cli and emp <>' ');
---- PROFESSIONNALS
commit;
----
*/