DROP SEQUENCE FF_SEQ_COMPTE_FLEX;
CREATE SEQUENCE  "FF_SEQ_COMPTE_FLEX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22000001 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
Truncate table STTB_UPLOAD_CUST_ACCOUNT_TD;
Truncate table STTB_UPLOAD_CUST_ACCOUNT_CASA;
Insert into STTB_UPLOAD_CUST_ACCOUNT_CASA
(
MAINTENANCE_SEQ_NO,
SOURCE_CODE,
BRANCH_CODE,
CUST_AC_NO,
AC_DESC,
CUST_NO,
CCY,
ACCOUNT_CLASS,
AC_STAT_NO_DR,
AC_STAT_NO_CR,
AC_STAT_BLOCK,
AC_STAT_STOP_PAY,
AC_STAT_DORMANT,
JOINT_AC_INDICATOR,
AC_OPEN_DATE,
AC_STMT_DAY,
AC_STMT_CYCLE,
ALT_AC_NO,
CHEQUE_BOOK_FACILITY,
ATM_FACILITY,
PASSBOOK_FACILITY,
AC_STMT_TYPE,
DR_HO_LINE,
CR_HO_LINE,
CR_CB_LINE,
DR_CB_LINE,
SUBLIMIT,
UNCOLL_FUNDS_LIMIT,
AC_STAT_FROZEN,
PREVIOUS_STATEMENT_DATE,
PREVIOUS_STATEMENT_BALANCE,
PREVIOUS_STATEMENT_NO,
TOD_LIMIT_START_DATE,
TOD_LIMIT_END_DATE,
TOD_LIMIT,
NOMINEE1,
NOMINEE2,
DR_GL,
CR_GL,
LIMIT_CCY,
LINE_ID,
OFFLINE_LIMIT,
CAS_ACCOUNT,
ACC_STMT_TYPE2,
ACC_STMT_DAY2,
AC_STMT_CYCLE2,
PREVIOUS_STATEMENT_DATE2,
PREVIOUS_STATEMENT_BALANCE2,
PREVIOUS_STATEMENT_NO2,
GEN_STMT_ONLY_ON_MVMT2,
ACC_STMT_TYPE3,
ACC_STMT_DAY3,
AC_STMT_CYCLE3,
PREVIOUS_STATEMENT_DATE3,
PREVIOUS_STATEMENT_BALANCE3,
PREVIOUS_STATEMENT_NO3,
GEN_STMT_ONLY_ON_MVMT3,
DR_AUTO_EX_RATE_LMT,
CR_AUTO_EX_RATE_LMT,
ADDRESS1,
ADDRESS2,
ADDRESS3,
ADDRESS4,
PINCODE,
TYPE_OF_CHQ,
ATM_CUST_AC_NO,
ATM_DLY_AMT_LIMIT,
ATM_DLY_COUNT_LIMIT,
GEN_STMT_ONLY_ON_MVMT,
AC_STAT_DE_POST,
DISPLAY_IBAN_IN_ADVICES,
CLEARING_BANK_CODE,
CLEARING_AC_NO,
IBAN_AC_NO,
REG_CC_AVAILABILITY,
MT210_REQD,
SWEEP_TYPE,
MIN_REQD_BAL,
DORMANT_PARAM,
POSITIVE_PAY_AC,
STALE_DAYS,
TRACK_RECEIVABLE,
REG_D_APPLICABLE,
REGD_PERIODICITY,
NETTING_REQUIRED,
LODGEMENT_BOOK_FACILITY,
REFERRAL_REQUIRED,
AUTO_REORDER_CHECK_REQUIRED,
AUTO_REORDER_CHECK_LEVEL,
AUTO_REORDER_CHECK_LEAVES,
CHECKBOOK_NAME_1,
CHECKBOOK_NAME_2,
ACC_STATUS,
STATUS_SINCE,
INHERIT_REPORTING,
OVERDRAFT_SINCE,
PREV_OVD_DATE,
STATUS_CHANGE_AUTOMATIC,
OVERLINE_OD_SINCE,
TOD_SINCE,
PREV_TOD_SINCE,
EXCL_SAMEDAY_RVRTRNS_FM_STMT,
ALLOW_BACK_PERIOD_ENTRY,
AUTO_PROV_REQD,
EXPOSURE_CATEGORY,
RISK_FREE_EXP_AMOUNT,
PROV_CCY_TYPE,
DEFER_RECON,
CONSOLIDATION_REQD,
ACTION_CODE,
FUNDING,
FUNDING_BRANCH,
FUNDING_ACCOUNT,
MOD9_VALIDATION_REQD,
VALIDATION_DIGIT,
PRODUCT_LIST,
TXN_CODE_LIST,
SPECIAL_CONDITION_PRODUCT,
SPECIAL_CONDITION_TXNCODE,
LOCATION,
MEDIA,
IBAN_REQD,
STATEMENT_ACCOUNT,
IBAN_BANK_CODE,
IBAN_ACC,
SOURCE_SEQ_NO,
AUTO_DEPOSITS_BAL,
MASTER_ACCOUNT_NO,
XREF,
OTHERDET,
GEN_INTERIM_STMT,
GEN_INTERIM_STMT_ON_MVMT,
GEN_BALANCE_REPORT,
INTERIM_REPORT_SINCE,
INTERIM_REPORT_TYPE,
BALANCE_REPORT_SINCE,
BALANCE_REPORT_TYPE,
INTERIM_DEBIT_AMT,
INTERIM_CREDIT_AMT,
INTERIM_STMT_DAY_COUNT,
INTERIM_STMT_YTD_COUNT,
DAYLIGHT_LIMIT_AMOUNT,
ESCROW_TRANSFER,
ESCROW_BRANCH_CODE,
ESCROW_AC_NO,
--ESCROW_PERCENTAGE,
AUTO_DC_REQUEST,
AUTO_CHQBK_REQUEST,
--INF_ACC_OPENING_AMT,
INF_PAY_IN_OPTION,
INF_OFFSET_BRANCH,
INF_OFFSET_ACCOUNT,
INF_WAIVE_ACC_OPEN_CHARGE,
ACCOUNT_TYPE,
SPEND_ANALYSIS_REQD,
GOAL_REF_NO,
AC_STAT_DR_OVD,
AC_STAT_CR_OVD,
DIRECT_BANKING,
SPL_AC_GEN,
MODE_OF_OPERATION,
MULTI_CCY_AC_NO,
UNCOLL_FUNDS_START_DT,
UNCOLL_FUNDS_END_DT,
DEF_SEQ,
STMT_OF_FEES_REQ,
STMT_OF_FEES_CYCLE,
--STMT_OF_FEES_ON,
STMT_OF_FEES_DEL_CHANNEL,
LAST_GENERATION_DATE,
LAST_STATEMENT_NO,
MULTI_CCY_IBAN_AC_NO,
RTL_REQUIRED,
CAMT_STMT_CYCLE--,
--CAMT_FREQUENCY,
--CAMT_FIXED_TIME
)
--create table sttbedelete as
Select 
FF_SEQ_COMPTE_FLEX.nextval MAINTENANCE_SEQ_NO	,
'AMPL_ACC_UPD'  SOURCE_CODE	,
FF_BRANCH_CODE(acc.age) BRANCH_CODE ,
'DUMMY' CUST_AC_NO,
trim(cl.nomrest) AC_DESC, -- dsam: 20220526 remapped from nom to nomrest 
rtrim(ltrim(acc.cli)) CUST_NO	,
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev))) CCY	,
FF_ACCOUNT_CLASS(acc.age, acc.ncp,acc.cli,acc.cpro) ACCOUNT_CLASS	, --FF_FROZEN_OR_OTHERS
FF_ACCOUNT_OPP(acc.age,acc.ncp,acc.dev,'NODEBIT') AC_STAT_NO_DR	,--FF_FROZEN_OR_OTHERS
FF_ACCOUNT_OPP(acc.age,acc.ncp,acc.dev,'NOCREDIT') AC_STAT_NO_CR	,
FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'16')  AC_STAT_BLOCK,
FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'14') AC_STAT_STOP_PAY,
FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'15') AC_STAT_DORMANT,
(case when acc.cptcoj='O' then 'J' else 'S' end) JOINT_AC_INDICATOR,
acc.dou AC_OPEN_DATE,
(case when acc.arr='O' then 31 else null end) AC_STMT_DAY	,
FF_ACCOUNT_PERIODICITE_ARR(acc.age,acc.ncp,acc.cli,acc.dev) AC_STMT_CYCLE	,
acc.age||acc.ncp||acc.clc ALT_AC_NO,
FF_CHEQUE_BOOK_FACILITY(acc.age,acc.cli,acc.ncp,acc.dev,acc.cha) CHEQUE_BOOK_FACILITY,
FF_ATM_FACILITY(acc.age,acc.cli,acc.ncp) ATM_FACILITY	,
'N' PASSBOOK_FACILITY,
'' AC_STMT_TYPE	, ---TOBEEXPLAIN
 FF_ACCOUNT_CLASS_DR_HO_LINE(acc.age,acc.ncp,acc.cli,acc.cpro) DR_HO_LINE	, --'BANKWAIT'
 FF_ACCOUNT_CLASS_CR_HO_LINE(acc.age,acc.ncp,acc.cli,acc.cpro) CR_HO_LINE	, --'BANKMTACC_CLASS'
FF_ACCOUNT_CLASS_CR_CB_LINE(acc.age,acc.ncp,acc.cli,acc.cpro) CR_CB_LINE	, --'BANKMTACC_CLASS'
FF_ACCOUNT_CLASS_DR_HO_LINE(acc.age,acc.ncp,acc.cli,acc.cpro) DR_CB_LINE	,
0 SUBLIMIT,
0 UNCOLL_FUNDS_LIMIT,
FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'08') AC_STAT_FROZEN,
FF_ACCOUNT_DATE_ARR(acc.age,acc.ncp,acc.cli,acc.dev) PREVIOUS_STATEMENT_DATE	,
FF_ACCOUNT_SOLDE_ARR(acc.age,acc.ncp,acc.cli,acc.dev) PREVIOUS_STATEMENT_BALANCE,
1 PREVIOUS_STATEMENT_NO,
--FF_OD_LIMIT_START_DATE(acc.age,acc.ncp,acc.dev) TOD_LIMIT_START_DATE	,
--FF_OD_LIMIT_END_DATE(acc.age,acc.ncp,acc.dev) TOD_LIMIT_END_DATE	,
NULL TOD_LIMIT_START_DATE	,  --- VALIDATION DJ 18112021
NULL TOD_LIMIT_END_DATE	, --- VALIDATION DJ 18112021
NULL TOD_LIMIT	,
NULL NOMINEE1	,
NULL NOMINEE2	,
FF_ACCOUNT_CLASS_DR_GL(acc.age,acc.ncp,acc.cli,acc.cpro) DR_GL	,
FF_ACCOUNT_CLASS_CR_GL(acc.age,acc.ncp,acc.cli,acc.cpro) CR_GL	, ---'BANKWAIT'
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev))) LIMIT_CCY ,
NULL LINE_ID,
0 OFFLINE_LIMIT,
FF_CAS_ACCOUNT(acc.age,acc.ncp,acc.dev) CAS_ACCOUNT	,
'N' ACC_STMT_TYPE2	,-----TO BE DETERMINE
NULL ACC_STMT_DAY2	,-----TO BE DETERMINE
NULL AC_STMT_CYCLE2	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_DATE2	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_BALANCE2,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_NO2,-----TO BE DETERMINE
'Y' GEN_STMT_ONLY_ON_MVMT2	,
NULL ACC_STMT_TYPE3	,-----TO BE DETERMINE
NULL ACC_STMT_DAY3	,-----TO BE DETERMINE
NULL AC_STMT_CYCLE3	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_DATE3	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_BALANCE3,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_NO3	,-----TO BE DETERMINE
'Y' GEN_STMT_ONLY_ON_MVMT3	,-----TO BE DETERMINE
NULL DR_AUTO_EX_RATE_LMT	,-----TO BE FASYL
NULL CR_AUTO_EX_RATE_LMT,-----TO BE DFASYL
FF_EMAIL_CLIENT_TIERS(acc.cli,'C') ADDRESS1,
NULL ADDRESS2	,
NULL ADDRESS3	,
NULL ADDRESS4	,
'' PINCODE	,
'' TYPE_OF_CHQ	,
NULL ATM_CUST_AC_NO	,
NULL ATM_DLY_AMT_LIMIT	,
0 ATM_DLY_COUNT_LIMIT	,
'N' GEN_STMT_ONLY_ON_MVMT	,
'Y' AC_STAT_DE_POST,
NULL DISPLAY_IBAN_IN_ADVICES,
'HEADOFFICE' CLEARING_BANK_CODE,
NULL CLEARING_AC_NO	,
'' IBAN_AC_NO	,--- TO BE INVOLDE
'' REG_CC_AVAILABILITY	, ---FASYL VALUES
(case when customer_type(acc.cli)='B' then 'Y' else 'N' end) MT210_REQD	,
1 SWEEP_TYPE	, ---VALUES BY FLEXCUBE
FF_MIN_REQD_BAL(acc.age,acc.ncp,acc.dev) MIN_REQD_BAL,
--FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'15') DORMANT_PARAM	,---to be confirm by the bank for the differents values
'M' DORMANT_PARAM ,
'N' POSITIVE_PAY_AC	,--to be confirm by the bank 
0 STALE_DAYS	,--- bank confirmation
'Y' TRACK_RECEIVABLE,-- bank confirmation
'N' REG_D_APPLICABLE,
'N' REGD_PERIODICITY,
'N' NETTING_REQUIRED,-- FASYL Confirmation
'N' LODGEMENT_BOOK_FACILITY	,
'Y' REFERRAL_REQUIRED	,--Bank confirmation FF_AUTO_REORDER_CHECK_LEAVES
(case when acc.seui!=0 then 'Y' else 'N' end) AUTO_REORDER_CHECK_REQUIRED	, -- bank confirmation
(case when FF_CHEQUE_BOOK_FACILITY(acc.age,acc.cli,acc.ncp,acc.dev,acc.cha)='O' THEN
  (case when acc.seui <= 100 then acc.seui else 100 end) else 0 end) AUTO_REORDER_CHECK_LEVEL,-- table to be update max value with 4digit
(case when FF_CHEQUE_BOOK_FACILITY(acc.age,acc.cli,acc.ncp,acc.dev,acc.cha)='O' then FF_AUTO_REORDER_CHECK_LEAVES(acc.tychq) else 0 end) AUTO_REORDER_CHECK_LEAVES	,
(case when FF_CHEQUE_BOOK_FACILITY(acc.age,acc.cli,acc.ncp,acc.dev,acc.cha)='N' then NULL else trim(CL.nom)||trim(CL.PRE) end) CHECKBOOK_NAME_1	,
NULL CHECKBOOK_NAME_2	,
'NORM' ACC_STATUS	, -- to be confirm
 NULL STATUS_SINCE	, -- to be confirm
'' INHERIT_REPORTING	, -- FASYL 
acc.dodb OVERDRAFT_SINCE	,
FF_PREV_OVD_DATE(acc.age,acc.ncp, acc.dev)PREV_OVD_DATE	,
'Y' STATUS_CHANGE_AUTOMATIC	,
NULL OVERLINE_OD_SINCE	,
NULL TOD_SINCE	,
NULL PREV_TOD_SINCE	,
NULL EXCL_SAMEDAY_RVRTRNS_FM_STMT	,---FASYL BACK
'Y' ALLOW_BACK_PERIOD_ENTRY,
'N' AUTO_PROV_REQD	, --- BANK CONFIRMATION
NULL EXPOSURE_CATEGORY	, ---BANK MAPPING --OMNIBSIC 28102021
NULL RISK_FREE_EXP_AMOUNT	,
'A' PROV_CCY_TYPE	, --- A or L
NULL DEFER_RECON	,---FASYL BACK
'N' CONSOLIDATION_REQD	, ---BANK Confirmation
'NEW' ACTION_CODE	,
NULL FUNDING	,
NULL FUNDING_BRANCH	,
NULL FUNDING_ACCOUNT	,
NULL MOD9_VALIDATION_REQD	,
NULL VALIDATION_DIGIT	,
'D' PRODUCT_LIST	, --- Disalloawed or Allowed
'D' TXN_CODE_LIST	, --- Disall or allowes
'' SPECIAL_CONDITION_PRODUCT	,
'' SPECIAL_CONDITION_TXNCODE	,
FF_LOCATION_CODE(cl.regn) LOCATION	,
'MAIL' MEDIA	,
'' IBAN_REQD	,
'' STATEMENT_ACCOUNT	,
'' IBAN_BANK_CODE	,
'' IBAN_ACC	,
FF_SEQ_COMPTE_FLEX.nextval SOURCE_SEQ_NO	,
0 AUTO_DEPOSITS_BAL	,
NULL MASTER_ACCOUNT_NO	, -----DEJI VALIDATION 18112021
'' XREF 	,
'' OTHERDET 	,
'N' GEN_INTERIM_STMT ,
'' GEN_INTERIM_STMT_ON_MVMT,--bk940
'' GEN_BALANCE_REPORT	,---bk940
'' INTERIM_REPORT_SINCE ,---bk940
'' INTERIM_REPORT_TYPE	,---bk94
NULL BALANCE_REPORT_SINCE 	,---FASYL VALUE
NULL BALANCE_REPORT_TYPE	,---FASYL
NULL INTERIM_DEBIT_AMT 	, --fasyl
NULL INTERIM_CREDIT_AMT	, --fasyl
NULL INTERIM_STMT_DAY_COUNT, --FASyl
0 INTERIM_STMT_YTD_COUNT,----FASYL value
NULL DAYLIGHT_LIMIT_AMOUNT	,--- bank
'N' ESCROW_TRANSFER	,
NULL ESCROW_BRANCH_CODE	,
NULL ESCROW_AC_NO,
--NULL ESCROW_PERCENTAGE,
'N' AUTO_DC_REQUEST	,
'N' AUTO_CHQBK_REQUEST,
--NULL INF_ACC_OPENING_AMT	,
NULL INF_PAY_IN_OPTION	,
NULL INF_OFFSET_BRANCH	,
NULL INF_OFFSET_ACCOUNT	,
'Y' INF_WAIVE_ACC_OPEN_CHARGE,
FF_ACCOUNT_TYPE(acc.age,acc.ncp,acc.dev) ACCOUNT_TYPE	,
'N' SPEND_ANALYSIS_REQD	,
NULL GOAL_REF_NO	,
'N' AC_STAT_DR_OVD	,--bank confirm : changed to N
'N' AC_STAT_CR_OVD	,
'N' DIRECT_BANKING	,
'N' SPL_AC_GEN	,
NULL MODE_OF_OPERATION	,--bank confi
NULL MULTI_CCY_AC_NO	,
NULL UNCOLL_FUNDS_START_DT	,
NULL UNCOLL_FUNDS_END_DT	,
NULL DEF_SEQ	,
NULL STMT_OF_FEES_REQ	,
NULL STMT_OF_FEES_CYCLE	,
--NULL STMT_OF_FEES_ON	,
NULL STMT_OF_FEES_DEL_CHANNEL	,
NULL LAST_GENERATION_DATE	,
NULL LAST_STATEMENT_NO	,
NULL MULTI_CCY_IBAN_AC_NO	,
'N' RTL_REQUIRED	,
'N' CAMT_STMT_CYCLE	--,
--NULL CAMT_FREQUENCY	,
--NULL CAMT_FIXED_TIME	
From BKCOM acc , BKCLI CL
where (acc.cha like '251%' or acc.cha like '253%' or acc.cha like '15_%')--typ in ('200','201','202','203','204','205','206','207','100')
and FF_ACCOUNT_CLASS(acc.age, acc.ncp,acc.cli,acc.cpro) is not null
and acc.cli=cl.cli and acc.cli is not null and acc.cli not like  ' %'
and acc.cfe  <> 'O'; -- remove closed accounts 20220513 dsam

commit;

-----
--select mnt1 from bknom where ctab='057'

--  Sttb_Upload_Linked_Entities linked entites
TRuncate TABLE STTB_UPLOAD_LINKED_ENTITIES;
--CREATE TABLE Sttb_Upload_Linked_Entities as
insert into Sttb_Upload_Linked_Entities
Select
FF_BRANCH_CODE(acc.age) BRANCH_CODE,
acc.age||acc.ncp||acc.clc CUST_AC_NO,
coj.cli JOINT_HOLDER_CODE,
coj.nom||' '||coj.pre JOINT_HOLDER_DESCRIPTION,
(case when coj.tco='C' then 'CUS' else 'AUS' end) JOINT_HOLDER,
ca.MAINTENANCE_SEQ_NO MAINTENANCE_SEQ_NO,
ca.SOURCE_SEQ_NO SOURCE_SEQ_NO,
ca.SOURCE_CODE,
sysdate START_DATE,
sysdate END_DATE

From bkcom acc, STTB_UPLOAD_CUST_ACCOUNT_Casa ca,bkcoj coj
where acc.age||acc.ncp||acc.clc=ca.ALT_AC_NO and coj.tco='C' --- update 05112021 Only Customer
and coj.clip=acc.cli and acc.cptcoj='O';
commit;


--- Account Status Table
-- STTM_STATUS_CHANGE_A_BAL_UPD

Truncate table STTM_STATUS_CHANGE_A_BAL_UPD;
   Insert into STTM_STATUS_CHANGE_A_BAL_UPD
   select acc.age||acc.ncp||acc.clc CUST_AC_NO,
   case when FF_ACCOUNT_OPP(acc.age,acc.ncp,acc.dev,'DORMANT')='Y' then acc.ddc else null end DATE_LAST_CR_ACTIVITY,
  case when FF_ACCOUNT_OPP(acc.age,acc.ncp,acc.dev,'DORMANT')='Y' then acc.ddd else null end DATE_LAST_DR_ACTIVITY,'' DATE_LAST_DR,'' DATE_LAST_CR,
   '' STATUS_SINCE,'NORM' ACC_STATUS, acc.dodb  OVERDRAFT_SINCE, FF_OVERDRAFT_SINCE(acc.age,acc.ncp,acc.dev) TOD_SINCE
   From BKCOM acc , BKCLI CL
where (acc.cha like '251%' or acc.cha like '253%' or acc.cha like '15_%')--typ in ('200','201','202','203','204','205','206','207','100')
and FF_ACCOUNT_CLASS(acc.age, acc.ncp,acc.cli,acc.cpro) is not null
and acc.cli=cl.cli and acc.cli is not null and acc.cli not like  ' %';

commit;


----------

----- insertion dans TD

--- Insertion dans TD

/* STOP BY NOVEMBER DECISISON TO UPLOAD TD AS LD
Truncate TABLE STTB_UPLOAD_CUST_ACCOUNT_TD;
Insert into STTB_UPLOAD_CUST_ACCOUNT_TD
(
MAINTENANCE_SEQ_NO,
SOURCE_CODE,
BRANCH_CODE,
CUST_AC_NO,
AC_DESC,
CUST_NO,
CCY,
ACCOUNT_CLASS,
AC_STAT_NO_DR,
AC_STAT_NO_CR,
AC_STAT_BLOCK,
AC_STAT_STOP_PAY,
AC_STAT_DORMANT,
JOINT_AC_INDICATOR,
AC_OPEN_DATE,
AC_STMT_DAY,
AC_STMT_CYCLE,
ALT_AC_NO,
CHEQUE_BOOK_FACILITY,
ATM_FACILITY,
PASSBOOK_FACILITY,
AC_STMT_TYPE,
DR_HO_LINE,
CR_HO_LINE,
CR_CB_LINE,
DR_CB_LINE,
SUBLIMIT,
UNCOLL_FUNDS_LIMIT,
AC_STAT_FROZEN,
PREVIOUS_STATEMENT_DATE,
PREVIOUS_STATEMENT_BALANCE,
PREVIOUS_STATEMENT_NO,
TOD_LIMIT_START_DATE,
TOD_LIMIT_END_DATE,
TOD_LIMIT,
NOMINEE1,
NOMINEE2,
DR_GL,
CR_GL,
LIMIT_CCY,
LINE_ID,
OFFLINE_LIMIT,
CAS_ACCOUNT,
ACC_STMT_TYPE2,
ACC_STMT_DAY2,
AC_STMT_CYCLE2,
PREVIOUS_STATEMENT_DATE2,
PREVIOUS_STATEMENT_BALANCE2,
PREVIOUS_STATEMENT_NO2,
GEN_STMT_ONLY_ON_MVMT2,
ACC_STMT_TYPE3,
ACC_STMT_DAY3,
AC_STMT_CYCLE3,
PREVIOUS_STATEMENT_DATE3,
PREVIOUS_STATEMENT_BALANCE3,
PREVIOUS_STATEMENT_NO3,
GEN_STMT_ONLY_ON_MVMT3,
DR_AUTO_EX_RATE_LMT,
CR_AUTO_EX_RATE_LMT,
ADDRESS1,
ADDRESS2,
ADDRESS3,
ADDRESS4,
PINCODE,
TYPE_OF_CHQ,
ATM_CUST_AC_NO,
ATM_DLY_AMT_LIMIT,
ATM_DLY_COUNT_LIMIT,
GEN_STMT_ONLY_ON_MVMT,
AC_STAT_DE_POST,
DISPLAY_IBAN_IN_ADVICES,
CLEARING_BANK_CODE,
CLEARING_AC_NO,
IBAN_AC_NO,
REG_CC_AVAILABILITY,
MT210_REQD,
SWEEP_TYPE,
MIN_REQD_BAL,
DORMANT_PARAM,
POSITIVE_PAY_AC,
STALE_DAYS,
TRACK_RECEIVABLE,
REG_D_APPLICABLE,
REGD_PERIODICITY,
NETTING_REQUIRED,
LODGEMENT_BOOK_FACILITY,
REFERRAL_REQUIRED,
AUTO_REORDER_CHECK_REQUIRED,
AUTO_REORDER_CHECK_LEVEL,
AUTO_REORDER_CHECK_LEAVES,
CHECKBOOK_NAME_1,
CHECKBOOK_NAME_2,
ACC_STATUS,
STATUS_SINCE,
INHERIT_REPORTING,
OVERDRAFT_SINCE,
PREV_OVD_DATE,
STATUS_CHANGE_AUTOMATIC,
OVERLINE_OD_SINCE,
TOD_SINCE,
PREV_TOD_SINCE,
EXCL_SAMEDAY_RVRTRNS_FM_STMT,
ALLOW_BACK_PERIOD_ENTRY,
AUTO_PROV_REQD,
EXPOSURE_CATEGORY,
RISK_FREE_EXP_AMOUNT,
PROV_CCY_TYPE,
DEFER_RECON,
CONSOLIDATION_REQD,
ACTION_CODE,
FUNDING,
FUNDING_BRANCH,
FUNDING_ACCOUNT,
MOD9_VALIDATION_REQD,
VALIDATION_DIGIT,
PRODUCT_LIST,
TXN_CODE_LIST,
SPECIAL_CONDITION_PRODUCT,
SPECIAL_CONDITION_TXNCODE,
LOCATION,
MEDIA,
IBAN_REQD,
STATEMENT_ACCOUNT,
IBAN_BANK_CODE,
IBAN_ACC,
SOURCE_SEQ_NO,
AUTO_DEPOSITS_BAL,
MASTER_ACCOUNT_NO,
XREF,
OTHERDET,
GEN_INTERIM_STMT,
GEN_INTERIM_STMT_ON_MVMT,
GEN_BALANCE_REPORT,
INTERIM_REPORT_SINCE,
INTERIM_REPORT_TYPE,
BALANCE_REPORT_SINCE,
BALANCE_REPORT_TYPE,
INTERIM_DEBIT_AMT,
INTERIM_CREDIT_AMT,
INTERIM_STMT_DAY_COUNT,
INTERIM_STMT_YTD_COUNT,
DAYLIGHT_LIMIT_AMOUNT,
ESCROW_TRANSFER,
ESCROW_BRANCH_CODE,
ESCROW_AC_NO,
--ESCROW_PERCENTAGE,
AUTO_DC_REQUEST,
AUTO_CHQBK_REQUEST,
--INF_ACC_OPENING_AMT,
INF_PAY_IN_OPTION,
INF_OFFSET_BRANCH,
INF_OFFSET_ACCOUNT,
INF_WAIVE_ACC_OPEN_CHARGE,
ACCOUNT_TYPE,
SPEND_ANALYSIS_REQD,
GOAL_REF_NO,
AC_STAT_DR_OVD,
AC_STAT_CR_OVD,
DIRECT_BANKING,
SPL_AC_GEN,
MODE_OF_OPERATION,
MULTI_CCY_AC_NO,
UNCOLL_FUNDS_START_DT,
UNCOLL_FUNDS_END_DT,
DEF_SEQ,
STMT_OF_FEES_REQ,
STMT_OF_FEES_CYCLE,
--STMT_OF_FEES_ON,
STMT_OF_FEES_DEL_CHANNEL,
LAST_GENERATION_DATE,
LAST_STATEMENT_NO,
MULTI_CCY_IBAN_AC_NO,
RTL_REQUIRED,
CAMT_STMT_CYCLE--,
--CAMT_FREQUENCY,
--CAMT_FIXED_TIME
)
--create table sttbedelete as

Select
FF_SEQ_COMPTE_FLEX.nextval MAINTENANCE_SEQ_NO	,
'AMPL_ACC_UPD'  SOURCE_CODE	,
FF_BRANCH_CODE(acc.age) BRANCH_CODE ,
NULL CUST_AC_NO,
cl.nom AC_DESC	,
rtrim(ltrim(acc.cli)) CUST_NO	,
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(com.dev))) CCY	,
FF_ACCOUNT_CLASS(com.age, acc.ncpd,com.cli,com.cpro) ACCOUNT_CLASS	, --FF_FROZEN_OR_OTHERS
FF_ACCOUNT_OPP(com.age, acc.ncpd,com.dev,'NODEBIT') AC_STAT_NO_DR	,--FF_FROZEN_OR_OTHERS
FF_ACCOUNT_OPP(com.age, acc.ncpd,com.dev,'NOCREDIT') AC_STAT_NO_CR	,
FF_FROZEN_OR_OTHERS(com.age, acc.ncpd,com.dev,'16')  AC_STAT_BLOCK,
FF_FROZEN_OR_OTHERS(com.age, acc.ncpd,com.dev,'14') AC_STAT_STOP_PAY,
FF_FROZEN_OR_OTHERS(com.age, acc.ncpd,com.dev,'15') AC_STAT_DORMANT,
(case when com.cptcoj='O' then 'J' else 'S' end) JOINT_AC_INDICATOR,
com.dou AC_OPEN_DATE,
(case when com.arr='O' then 31 else null end) AC_STMT_DAY	,
FF_ACCOUNT_PERIODICITE_ARR(com.age,acc.ncpd,com.cli,com.dev) AC_STMT_CYCLE	,
com.age||acc.ncpd||com.clc ALT_AC_NO,
FF_CHEQUE_BOOK_FACILITY(com.age,com.cli,com.ncp,com.dev,com.cha) CHEQUE_BOOK_FACILITY,
--FF_ATM_FACILITY(acc.age,acc.cli,acc.ncp) ATM_FACILITY	,
'N' ATM_FACILITY	,
'N' PASSBOOK_FACILITY,
'' AC_STMT_TYPE	, ---TOBEEXPLAIN
 FF_ACCOUNT_CLASS_DR_HO_LINE(com.age,acc.ncpd,com.cli,com.cpro) DR_HO_LINE	, --'BANKWAIT'
 FF_ACCOUNT_CLASS_CR_HO_LINE(com.age,acc.ncpd,com.cli,com.cpro) CR_HO_LINE	, --'BANKMTACC_CLASS'
FF_ACCOUNT_CLASS_CR_CB_LINE(com.age,acc.ncpd,com.cli,com.cpro) CR_CB_LINE	, --'BANKMTACC_CLASS'
FF_ACCOUNT_CLASS_DR_CB_LINE(com.age,acc.ncpd,com.cli,com.cpro) DR_CB_LINE	,
0 SUBLIMIT,
0 UNCOLL_FUNDS_LIMIT,
FF_FROZEN_OR_OTHERS(com.age,acc.ncpd,com.dev,'08') AC_STAT_FROZEN,
FF_ACCOUNT_DATE_ARR(com.age,acc.ncpd,com.cli,com.dev) PREVIOUS_STATEMENT_DATE	,
FF_ACCOUNT_SOLDE_ARR(com.age,com.ncp,com.cli,com.dev) PREVIOUS_STATEMENT_BALANCE,
1 PREVIOUS_STATEMENT_NO,
FF_OD_LIMIT_START_DATE(com.age,com.ncp,com.dev) TOD_LIMIT_START_DATE	,
FF_OD_LIMIT_END_DATE(com.age,com.ncp,com.dev) TOD_LIMIT_END_DATE	,
NULL TOD_LIMIT	,
NULL NOMINEE1	,
NULL NOMINEE2	,
FF_ACCOUNT_CLASS_DR_GL(com.age,acc.ncpd,com.cli,com.cpro) DR_GL	,
FF_ACCOUNT_CLASS_CR_GL(com.age,acc.ncpd,com.cli,com.cpro) CR_GL	, ---'BANKWAIT'
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(com.dev))) LIMIT_CCY ,
NULL LINE_ID,
0 OFFLINE_LIMIT,
FF_CAS_ACCOUNT(com.age,com.ncp,com.dev) CAS_ACCOUNT	,
'N' ACC_STMT_TYPE2	,-----TO BE DETERMINE
NULL ACC_STMT_DAY2	,-----TO BE DETERMINE
NULL AC_STMT_CYCLE2	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_DATE2	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_BALANCE2,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_NO2,-----TO BE DETERMINE
'Y' GEN_STMT_ONLY_ON_MVMT2	,
NULL ACC_STMT_TYPE3	,-----TO BE DETERMINE
NULL ACC_STMT_DAY3	,-----TO BE DETERMINE
NULL AC_STMT_CYCLE3	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_DATE3	,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_BALANCE3,-----TO BE DETERMINE
NULL PREVIOUS_STATEMENT_NO3	,-----TO BE DETERMINE
'Y' GEN_STMT_ONLY_ON_MVMT3	,-----TO BE DETERMINE
NULL DR_AUTO_EX_RATE_LMT	,-----TO BE FASYL
NULL CR_AUTO_EX_RATE_LMT,-----TO BE DFASYL
FF_EMAIL_CLIENT_TIERS(com.cli,'C') ADDRESS1,
NULL ADDRESS2	,
NULL ADDRESS3	,
NULL ADDRESS4	,
'' PINCODE	,
'' TYPE_OF_CHQ	,
NULL ATM_CUST_AC_NO	,
NULL ATM_DLY_AMT_LIMIT	,
0 ATM_DLY_COUNT_LIMIT	,
'N' GEN_STMT_ONLY_ON_MVMT	,
'Y' AC_STAT_DE_POST,
NULL DISPLAY_IBAN_IN_ADVICES, --OMNIBSIC 28102021
'' CLEARING_BANK_CODE,
NULL CLEARING_AC_NO	,
'' IBAN_AC_NO	,--- TO BE INVOLDE
'' REG_CC_AVAILABILITY	, ---FASYL VALUES
(case when customer_type(com.cli)='B' then 'Y' else 'N' end) MT210_REQD	,
NULL SWEEP_TYPE	, ---VALUES BY FLEXCUBE
FF_MIN_REQD_BAL(com.age,com.ncp,com.dev) MIN_REQD_BAL,
--FF_FROZEN_OR_OTHERS(acc.age,acc.ncp,acc.dev,'15') DORMANT_PARAM	,---to be confirm by the bank for the differents values
'M' DORMANT_PARAM ,
'N' POSITIVE_PAY_AC	,--to be confirm by the bank 
0 STALE_DAYS	,--- bank confirmation
'Y' TRACK_RECEIVABLE,-- bank confirmation
'N' REG_D_APPLICABLE,
'N' REGD_PERIODICITY,
'N' NETTING_REQUIRED,-- FASYL Confirmation
'N' LODGEMENT_BOOK_FACILITY	,
'Y' REFERRAL_REQUIRED	,--Bank confirmation
(case when com.seui!=0 then 'Y' else 'N' end) AUTO_REORDER_CHECK_REQUIRED	, -- bank confirmation
(case when FF_CHEQUE_BOOK_FACILITY(com.age,com.cli,com.ncp,com.dev,com.cha)='O' THEN
  (case when com.seui <= 100 then com.seui else 100 end) else 0 end) AUTO_REORDER_CHECK_LEVEL,-- table to be update max value with 4digit
(case when FF_CHEQUE_BOOK_FACILITY(com.age,com.cli,com.ncp,com.dev,com.cha)='O' then FF_AUTO_REORDER_CHECK_LEAVES(com.tychq) else 0 end) AUTO_REORDER_CHECK_LEAVES	,
(case when FF_CHEQUE_BOOK_FACILITY(com.age,com.cli,com.ncp,com.dev,com.cha)='N' then NULL else trim(CL.nom)||trim(CL.PRE) end) CHECKBOOK_NAME_1	,
NULL CHECKBOOK_NAME_2	,
'NORM' ACC_STATUS	, -- to be confirm
 NULL STATUS_SINCE	, -- to be confirm
'' INHERIT_REPORTING	, -- FASYL 
com.dodb OVERDRAFT_SINCE	,
FF_PREV_OVD_DATE(com.age,com.ncp, com.dev)PREV_OVD_DATE	,
'Y' STATUS_CHANGE_AUTOMATIC	,
NULL OVERLINE_OD_SINCE	,
NULL TOD_SINCE	,
NULL PREV_TOD_SINCE	,
NULL EXCL_SAMEDAY_RVRTRNS_FM_STMT	,---FASYL BACK
'Y' ALLOW_BACK_PERIOD_ENTRY,
'N' AUTO_PROV_REQD	, --- BANK CONFIRMATION
NULL EXPOSURE_CATEGORY	, ---BANK MAPPING OMNSIBIC 22102021
NULL RISK_FREE_EXP_AMOUNT	,
'A' PROV_CCY_TYPE	, --- A or L
NULL DEFER_RECON	,---FASYL BACK
'N' CONSOLIDATION_REQD	, ---BANK Confirmation
'NEW' ACTION_CODE	,
NULL FUNDING	,
NULL FUNDING_BRANCH	,
NULL FUNDING_ACCOUNT	,
NULL MOD9_VALIDATION_REQD	,
NULL VALIDATION_DIGIT	,
'D' PRODUCT_LIST	, --- Disalloawed or Allowed
'D' TXN_CODE_LIST	, --- Disall or allowes
'' SPECIAL_CONDITION_PRODUCT	,
'' SPECIAL_CONDITION_TXNCODE	,
FF_LOCATION_CODE(cl.regn) LOCATION	,
'MAIL' MEDIA	,
'' IBAN_REQD	,
'' STATEMENT_ACCOUNT	,
'' IBAN_BANK_CODE	,
'' IBAN_ACC	,
FF_SEQ_COMPTE_FLEX.nextval SOURCE_SEQ_NO	,
0 AUTO_DEPOSITS_BAL	,
NULL MASTER_ACCOUNT_NO	, --- DEJI VALIDATION 18112021
'' XREF 	,
'' OTHERDET 	,
'N' GEN_INTERIM_STMT ,
'' GEN_INTERIM_STMT_ON_MVMT,--bk940
'' GEN_BALANCE_REPORT	,---bk940
'' INTERIM_REPORT_SINCE ,---bk940
'' INTERIM_REPORT_TYPE	,---bk94
NULL BALANCE_REPORT_SINCE 	,---FASYL VALUE
NULL BALANCE_REPORT_TYPE	,---FASYL
NULL INTERIM_DEBIT_AMT 	, --fasyl
NULL INTERIM_CREDIT_AMT	, --fasyl
NULL INTERIM_STMT_DAY_COUNT, --FASyl
0 INTERIM_STMT_YTD_COUNT,----FASYL value
NULL DAYLIGHT_LIMIT_AMOUNT	,--- bank
'N' ESCROW_TRANSFER	,
NULL ESCROW_BRANCH_CODE	,
NULL ESCROW_AC_NO,
--NULL ESCROW_PERCENTAGE,
'N' AUTO_DC_REQUEST	,
'N' AUTO_CHQBK_REQUEST,
--NULL INF_ACC_OPENING_AMT	,
NULL INF_PAY_IN_OPTION	,
NULL INF_OFFSET_BRANCH	,
NULL INF_OFFSET_ACCOUNT	,
'Y' INF_WAIVE_ACC_OPEN_CHARGE,
FF_ACCOUNT_TYPE(com.age,acc.ncpd,com.dev) ACCOUNT_TYPE	,
'N' SPEND_ANALYSIS_REQD	,
NULL GOAL_REF_NO	,
'Y' AC_STAT_DR_OVD	,--bank confirm
'N' AC_STAT_CR_OVD	,
'N' DIRECT_BANKING	,
'N' SPL_AC_GEN	,
NULL MODE_OF_OPERATION	,--bank confi
NULL MULTI_CCY_AC_NO	,
NULL UNCOLL_FUNDS_START_DT	,
NULL UNCOLL_FUNDS_END_DT	,
NULL DEF_SEQ	,
NULL STMT_OF_FEES_REQ	,
NULL STMT_OF_FEES_CYCLE	,
--NULL STMT_OF_FEES_ON	,
NULL STMT_OF_FEES_DEL_CHANNEL	,
NULL LAST_GENERATION_DATE	,
NULL LAST_STATEMENT_NO	,
NULL MULTI_CCY_IBAN_AC_NO	,
'N' RTL_REQUIRED	,
'N' CAMT_STMT_CYCLE	--,
--NULL CAMT_FREQUENCY	,
--NULL CAMT_FIXED_TIME	
From BKDAT acc, BKCOM COM , BKCLI CL where customer_type(com.cli)='I' and CL.cli=com.cli
 and com.ncp=acc.ncpd and com.age=acc.age and com.cli=acc.cli 
and FF_ACCOUNT_CLASS(com.age, acc.ncpd,com.cli,com.cpro) is not null
and ctr not in ('6','7','9','8');
commit;
*/



