
--- AMOUNT BLOCK SCRIPT CREATION CATM_UPLOAD_AMOUNT_BLOCKS
 /*CREATE TABLE CATM_UPLOAD_AMOUNT_BLOCKS
   (	"MAINTENANCE_SEQ_NO" VARCHAR2(16 BYTE), 
	"SOURCE_CODE" VARCHAR2(15 BYTE), 
	"BRANCH_CODE" VARCHAR2(3 BYTE), 
	"ACCOUNT_NO" VARCHAR2(20 BYTE), 
	"AMOUNT_BLOCK_NO" NUMBER(19,0), 
	"AMOUNT" NUMBER(19,4), 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"REMARKS" VARCHAR2(255 BYTE), 
	"UPLOAD_STATUS_FLAG" CHAR(1 BYTE), 
	"ERRMSG" VARCHAR2(255 BYTE), 
	"AMOUNT_BLOCK_TYPE" VARCHAR2(1 BYTE), 
	"REFERENCE_NO" VARCHAR2(40 BYTE), 
	"HOLD_CODE" VARCHAR2(15 BYTE), 
	"FUND_AVL_CHECK" VARCHAR2(1 BYTE)
   ) ;
*/
--CATM_UPLOAD_AMOUNT_BLOCKS
DROP SEQUENCE FF_SEQ_AMOUNT_BLOCKS_FLEX;
CREATE SEQUENCE  "FF_SEQ_AMOUNT_BLOCKS_FLEX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 52000001 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
Truncate table CATM_UPLOAD_AMOUNT_BLOCKS;
--FF_SEQ_AMOUNT_BLOCKS_FLEX.nextval MAINTENANCE_SEQ_NO	
 --CREATE TABLE CATM_UPLOAD_AMOUNT_BLOCKS as
 Insert into CATM_UPLOAD_AMOUNT_BLOCKS
Select FF_SEQ_AMOUNT_BLOCKS_FLEX.nextval MAINTENANCE_SEQ_NO	,
'AMPL_AMTBLK_UPD' SOURCE_CODE,
FF_BRANCH_CODE(acc.age) BRANCH_CODE,
com.age||acc.ncp1||com.clc ACCOUNT_NO,
NULL AMOUNT_BLOCK_NO,
acc.mon1 AMOUNT,
acc.dco EFFECTIVE_DATE,
acc.dech EXPIRY_DATE,
acc.LIB1 REMARKS,
'U' UPLOAD_STATUS_FLAG,
NULL ERRMSG,
NULL AMOUNT_BLOCK_TYPE,
acc.eve REFERENCE_NO,
'AMPLITUDE' HOLD_CODE,
'N' FUND_AVL_CHECK
From BKEVE acc, BKCOM com where acc.eta in  ('VA','FO') and acc.ORIG='S'
and acc.nat='RESERV'  and com.ncp=acc.ncp1 and com.age=acc.age;

commit;

--select * from CATM_UPLOAD_AMOUNT_BLOCKS;

/*
CREATE TABLE STTM_DENM_REDM_BLK_UPLD (
MAINTENANCE_SEQ_NO	VARCHAR2(16),
SOURCE_CODE	VARCHAR2(15),
BRANCH_CODE	VARCHAR2(3),
CUST_AC_NO	VARCHAR2(20),
CERTIFICATE_NO	VARCHAR2(16),
REFERENCE_NO	VARCHAR2(35),
CERTIFICATE_AMOUNT	NUMBER(22,3),
BLOCK_OR_REDEM	VARCHAR2(1),
CERTIFICATE_STATUS	VARCHAR2(1) ) ;


INSERT INTO STTM_DENM_REDM_BLK_UPLD 
Select 
MAINTENANCE_SEQ_NO	,
SOURCE_CODE,
BRANCH_CODE	,
CUST_AC_NO	,
CERTIFICATE_NO	,
REFERENCE_NO	,
CERTIFICATE_AMOUNT	,
BLOCK_OR_REDEM	,
CERTIFICATE_STATUS	

FROM BKBDC ACC

*/
