Truncate table LDTB_UPLOAD_SCHEDULES;
Insert into LDTB_UPLOAD_SCHEDULES
Select
acc.EXT_CONTRACT_REF_NO  EXT_CONTRACT_REF_NO,
acc.SOURCE_CODE SOURCE_CODE,
acc.BRANCH BRANCH_CODE,
'PRINCIPAL' COMPONENT,
'P' SCHEDULE_TYPE,
DAT.DECH START_DATE,
1 NO_OF_SCHEDULES,
1 FREQUENCY_UNIT,
acc.AMOUNT  AMOUNT,
'B' FREQUENCY,
NULL UPLOAD_ID,
'CDDTRONL' FUNCTION_ID ,
acc.SOURCE_SEQ_NO  SOURCE_SEQ_NO,
'NEW' ACTION_CODE
FRom Ldtb_Upload_Master acc, BKDAT DAT
Where acc.EXT_CONTRACT_REF_NO=DAT.EVE
and acc.BRANCH=FF_BRANCH_CODE(DAT.age)

UNION ALL
Select
acc.EXT_CONTRACT_REF_NO  EXT_CONTRACT_REF_NO,
acc.SOURCE_CODE SOURCE_CODE,
acc.BRANCH BRANCH_CODE,
'CD_MAINCOM' COMPONENT, -- replace CD_MAINCOM by CD_COMP 05042022
'P' SCHEDULE_TYPE,
DAT.DECH START_DATE,
1 NO_OF_SCHEDULES,
1 FREQUENCY_UNIT,
NULL  AMOUNT,
'B' FREQUENCY,
NULL UPLOAD_ID,
'CDDTRONL' FUNCTION_ID ,
acc.SOURCE_SEQ_NO  SOURCE_SEQ_NO,
'NEW' ACTION_CODE
FRom Ldtb_Upload_Master acc, BKDAT DAT
Where acc.EXT_CONTRACT_REF_NO=DAT.EVE
and acc.BRANCH=FF_BRANCH_CODE(DAT.age)
;

commit;