--- Sitb_Upload_Master
DROP SEQUENCE FF_SEQ_SITBUPLOAD_FLEX;
CREATE SEQUENCE  "FF_SEQ_SITBUPLOAD_FLEX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 92000001 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

--------
-- Master Data For SWEEPING
---------
define DATE_PARAM='31/07/2022';
Truncate table Sitb_Upload_Master;
Truncate table Sitb_Upload_Instruction;
INSERT INTO Sitb_Upload_Master  


Select 
FF_BRANCH_CODE(acc.age) BRANCH_CODE	,-- bank mapping
'AMPL_SI' SOURCE_CODE	,--AMP_SI
--FF_SEQ_SITBUPLOAD_FLEX.nextval SOURCE_REF	,-- correct 20122021
acc.eve SOURCE_REF,
NULL DETAIL_REF	,--generated by flexcube default=NULL
--FF_SEQ_SITBUPLOAD_FLEX.nextval USER_REF_NUMBER	,--SOURCE_REF
acc.eve USER_REF_NUMBER, --correct 20122021
acc.dech SI_EXPIRY_DATE,--	
acc.dapp BOOK_DATE	,--
'SOCU' PRODUCT_CODE, --FF_SI_PRODUCT_CODE(acc.typt,acc.ope) PRODUCT_CODE	,--bank mapping correct 20122021
substr(acc.clid,1,9) COUNTERPARTY	,-- to be load 31032022
'O' PRODUCT_TYPE,
--FF_SI_PRODUCT_TYPE(acc.typt,acc.ope) PRODUCT_TYPE	,--Payements bkvrt 'P',SweepInt bkvcd - bkcvc 'I' , Sweepout bkcvt 'O' ,Collection 'C',VariablePayment 'V' ,RangeBalanceSweep
NULL SERIAL_NO	,--default=NULL
'F' ACTION_CODE_AMT	,--Full Pending  , Partial Executing, Ignore Waiting, Force
'Y' APPLY_CHG_SUXS	,--default=Y bank decision
'N' APPLY_CHG_PEXC	,--default=Y bank decision  correct 20122021
'N' APPLY_CHG_REJT	,--default=Y bank decision   correct 20122021
5 MAX_RETRY_COUNT	,--see bank parameters  correct 20122021
acc.msolde IN_SWEEP_AMT	,--default amplitude values FASYL will translate
FF_BRANCH_CODE(acc.aged) DR_ACC_BR	,--default amplitude values FASYL will translate
 acc.aged||acc.ncpd||acc.clcd DR_ACCOUNT	,--default amplitude values FASYL will translate
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.devd))) DR_ACC_CCY	,--default amplitude values FASYL will translate
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev))) SI_AMT_CCY	,--default amplitude values FASYL will translate
msldt SI_AMT	,--default amplitude values FASYL will translate
FF_BRANCH_CODE(acc.agec) CR_ACC_BR	,--default amplitude values FASYL will translate
acc.age||acc.ncpc||acc.clcc CR_ACCOUNT	,--default amplitude values FASYL will translate
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.devc))) CR_ACC_CCY	,--default amplitude values FASYL will translate
1 PRIORITY, --acc.prio PRIORITY	correct 20122021,--define the priority order for multiples instructions in the same day default=1 bank decision
'R' CHARGE_WHOM	,--default=R others values Beneficiary
acc.msolde MIN_BAL_AFTER_SWEEP	,--acc.msolde MIN_BAL_AFTER_SWEEP	,--solde minimum sur le compte aprés un sweep
'' INTERNAL_REMARKS,--	
'' ICCF_CHANGED	,--motif ou libellé
'' TAX_CHANGED	,--
'' SETTLE_CHANGED	,--
'' MIS_CHANGED	,--
'U' CONV_STATUS,--	default=O
NULL ERR_MSG	,--
'A' AUTHORIZE	,--correct 20122021
acc.eve CONTRACT_REF_NO,--NO	SOURCE_REF correct 20122021 change value to NULL
1 VERSION_NO,--	default=1
NULL INSTRUCTION_NO,--	SOURCE_REF correct 20122021 change eve value to NULL
1 TRANSFER_TYPE,--	default=NULL change from NULL to 1 20122021 
NULL SUBSYSTEM_STAT,--	default=NULL
'SIDTRONL' FUNCTION_ID	,--default=SIDTRONL
FF_SEQ_SITBUPLOAD_FLEX.nextval SOURCE_SEQ_NO,	
NULL UPLOAD_ID	,--same as SOURCE_SEQ_NO change from FF_SEQ_SITBUPLOAD_FLEX to NULL 20122021
'NEW' ACTION_CODE,--	NEW
3 RETRY_COUNT_ADV,	--nombres maximum d'echecs
NULL UPP_RANGE_BAL_LIM, ---NEW FIELD ADD 20122021
NULL LOW_RANGE_BAL_LIM, ---NEW FIELD ADD 20122021
NULL UI_DR_ACCOUNT, ---NEW FIELD ADD 20122021
NULL UI_CR_ACCOUNT ---NEW FIELD ADD 20122021
From bkvcd acc
where acc.eta in ('VA','FO') and ctr!='9'
and msldt <> 0   -- dsam: remove SI with 0 transfer amount
and dech > '&DATE_PARAM'; --dsam: added 20220420 -- remove expired SI
commit;
----------
-- SI Details Instructions for SWEEPING 
---------
Insert into Sitb_Upload_Instruction
Select 
acc.BRANCH_CODE BRANCH_CODE	,--mapping bank
acc.SOURCE_CODE SOURCE_CODE,--	AMP_SI
acc.SOURCE_REF	SOURCE_REF,--
acc.PRODUCT_CODE PRODUCT_CODE,--	mapping of bank
acc.PRODUCT_TYPE PRODUCT_TYPE,--	Payements,SweepInt, Sweepout,Collection,VariablePayment,RangeBalanceSweep
1 SI_TYPE	,--One to one=1, One to Many=2, Many to One=3,  Many to Many=4
'F' CAL_HOL_EXCP,--	Forward, Backward, Lapse (default=B)
'STANDARD' RATE_TYPE,--	default=STANDARD
(case when vcd.per  in ('H','J') then vcd.DAY else null end) EXEC_DAYS,--	
(case when vcd.per='M' then vcd.DAY else null end) EXEC_MTHS,--	
(case when vcd.per='A' then vcd.DAY else null end) EXEC_YRS	,--
--vcd.dapp FIRST_EXEC_DATE	,--
(
	case when per = 'J' then sysdate+1 -- dsam: added 20220421
		 when per = 'H' then sysdate+7
		 when per = 'M' then sysdate+30
		 when per = 'A' then sysdate+365
	end
) FIRST_EXEC_DATE,

(
	case when per = 'J' then sysdate+2 -- dsam: added 20220421
		 when per = 'H' then sysdate+14
		 when per = 'M' then sysdate+60
		 when per = 'A' then sysdate+730
	end
) NEXT_EXEC_DATE,

(
	case when per = 'J' then sysdate+1 -- dsam: added 20220421
		 when per = 'H' then sysdate+7
		 when per = 'M' then sysdate+30
		 when per = 'A' then sysdate+365
	end
) FIRST_VALUE_DATE,

(
	case when per = 'J' then sysdate+2 -- dsam: added 20220421
		 when per = 'H' then sysdate+14
		 when per = 'M' then sysdate+60
		 when per = 'A' then sysdate+730
	end
) NEXT_VALUE_DATE,


/*
NEXT_EXEC_DATE
(
vcd.per,vcd.DAY
, vcd.ope ,
vcd.dapp ,
vcd.ddtf ,
vcd.ddech ) NEXT_EXEC_DATE	,--  a revoir
*/

--nvl(vcd.dva1,vcd.dapp) FIRST_VALUE_DATE	,--



/*
NEXT_VALUE_DATE('000',NEXT_EXEC_DATE
(
vcd.per,vcd.DAY, 
vcd.ope ,
vcd.dapp ,
vcd.ddtf ,
vcd.ddech ),'00')  NEXT_VALUE_DATE	,-- a revoir
*/


'N' MONTH_END_FLAG,--	default=N it depend on instructions
'E' PROCESSING_TIME	,--End of day=default, Begining of day
--acc.USER_REF_NUMBER USER_INST_NO	,--USER_ref_no FROM THE MASTER UPLOAD
NULL USER_INST_NO,
'A' INST_STATUS,--	DEFAULT = A
'A' AUTH_STATUS,--	Default=A
vcd.dmo LATEST_VERSION_DATE	,--
vcd.ddem BOOK_DATE	,--
'' SERIAL_NO	,--
substr(vcd.clid,1,9) COUNTERPARTY	,--
'' LATEST_CYCLE_NO	,--
vcd.ddtf LATEST_CYCLE_DATE	,--
'U' CONV_STATUS	,-- 20122021
NULL ERR_MSG	,--
NULL GEN_MESG	,--default=NULL
Acc.SOURCE_REF INSTRUCTION_NO	,--SOURCE_REF
1 INST_VERSION_NO,--	default=1
NULL OPERATION	,--default=NULL
'SIDTRONL' FUNCTION_ID	,--default=SIDTRONL
Acc.SOURCE_SEQ_NO SOURCE_SEQ_NO	,--
NULL UPLOAD_ID	,--same as SOURCE_SEQ_NO  20122021
'NEW' ACTION_CODE	,--default=NEW
'N' SUSPEND_EXECUTION,--	default=N
NULL GOAL_REF_NO,	--default=NULL
NULL GROUP_CODE
From Sitb_Upload_Master Acc, bkvcd vcd 
where vcd.eta in ('VA','FO') and ctr!='9' and vcd.eve=acc.contract_ref_no and acc.product_code in ('SOCU');

commit;


-------- END DETAILS -----------------------------------

-------- VIREMENT PERMANENT ---------

--select * from Sitb_Upload_Master
INSERT INTO Sitb_Upload_Master  
Select 
FF_BRANCH_CODE(acc.age) BRANCH_CODE	,-- bank mapping
'AMPL_SI' SOURCE_CODE	,--AMP_SI
FF_SEQ_SITBUPLOAD_FLEX.nextval SOURCE_REF	,--
NULL DETAIL_REF	,--generated by flexcube default=NULL
FF_SEQ_SITBUPLOAD_FLEX.nextval USER_REF_NUMBER	,--SOURCE_REF
acc.dde SI_EXPIRY_DATE,--	
acc.dco BOOK_DATE	,--
FF_SI_PRODUCT_CODE(acc.typv,acc.ope) PRODUCT_CODE	,--bank mapping
substr(acc.cli1,1,9) COUNTERPARTY	,--
'P'  PRODUCT_TYPE,
--FF_SI_PRODUCT_TYPE(acc.typt,acc.ope) PRODUCT_TYPE	,--Payements bkvrt 'P',SweepInt bkvcd - bkcvc 'I' , Sweepout bkcvt 'O' ,Collection 'C',VariablePayment 'V' ,RangeBalanceSweep
NULL SERIAL_NO	,--default=NULL
'F' ACTION_CODE_AMT	,--Full Pending  , Partial Executing, Ignore Waiting, Force
'Y' APPLY_CHG_SUXS	,--default=Y bank decision
'N' APPLY_CHG_PEXC	,--default=Y bank decision correc 27122021
'N' APPLY_CHG_REJT	,--default=Y bank decision  correc 27122021
5 MAX_RETRY_COUNT	,--see bank parameters
acc.mont IN_SWEEP_AMT	,--default amplitude values FASYL will translate
FF_BRANCH_CODE(acc.age1) DR_ACC_BR	,--default amplitude values FASYL will translate
 acc.age1||acc.ncp1||acc.clc1 DR_ACCOUNT	,--default amplitude values FASYL will translate
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev1))) DR_ACC_CCY	,--default amplitude values FASYL will translate
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev))) SI_AMT_CCY	,--default amplitude values FASYL will translate
--mont SI_AMT	,--default amplitude values FASYL will translate
mdev SI_AMT , -- dsam: added 20220420
FF_BRANCH_CODE(acc.age2) CR_ACC_BR	,--default amplitude values FASYL will translate
--NVL(acc.age2||acc.ncp2||acc.clc2,trim(acc.ETAB)||trim(acc.guib)||trim(acc.cpte)||trim(acc.cleb)) CR_ACCOUNT	,--default amplitude values FASYL will translate
NVL(acc.age2||acc.ncp2||acc.clc2,trim(acc.ETAB)||trim(acc.cpte)) CR_ACCOUNT	,
rtrim(ltrim(FF_DEVISE_ISO3LETTRE(acc.dev2))) CR_ACC_CCY	,--default amplitude values FASYL will translate
1 PRIORITY	,--define the priority order for multiples instructions in the same day default=1 bank decision
'R' CHARGE_WHOM	,--default=R others values Beneficiary
0 MIN_BAL_AFTER_SWEEP	,--acc.msolde MIN_BAL_AFTER_SWEEP	,--solde minimum sur le compte aprés un sweep
'' INTERNAL_REMARKS,--	
'' ICCF_CHANGED	,--motif ou libellé
'' TAX_CHANGED	,--
'' SETTLE_CHANGED	,--
'' MIS_CHANGED	,--
'U' CONV_STATUS,--	default=O correct 27122021
NULL ERR_MSG	,--  correct 27122021
'A' AUTHORIZE	,--
acc.eve CONTRACT_REF_NO,--NO	SOURCE_REF correct 27122021
1 VERSION_NO,--	default=1
NULL INSTRUCTION_NO,--	SOURCE_REF correct 27122021
1 TRANSFER_TYPE,--	default=NULL
NULL SUBSYSTEM_STAT,--	default=NULL
'SIDTRONL' FUNCTION_ID	,--default=SIDTRONL
FF_SEQ_SITBUPLOAD_FLEX.nextval SOURCE_SEQ_NO,	
NULL UPLOAD_ID	,--same as SOURCE_SEQ_NO correct 27122021
'NEW' ACTION_CODE,--	NEW
3 RETRY_COUNT_ADV,	--nombres maximum d'echecs
NULL UPP_RANGE_BAL_LIM, ---NEW FIELD ADD 20122021
NULL LOW_RANGE_BAL_LIM, ---NEW FIELD ADD 20122021
NULL UI_DR_ACCOUNT, ---NEW FIELD ADD 20122021
NULL UI_CR_ACCOUNT ---NEW FIELD ADD 20122021	--nombres maximum d'echecs

From bkvrt acc
where acc.eta in ('VA','FO') and acc.dde>'&DATE_PARAM' -- and ctr!='9' ;
and acc.mdev <> 0 -- dsam: remove SI with 0 transfer amount
and acc.resi is null ; -- dsam:  remove terminated SI

commit;
---- FIN VIREMENT PERMANENT ----------

---- PERMANENT VIREMENT INSTRUCTIONS----
--   select *  from Sitb_Upload_Instruction
Insert Into Sitb_Upload_Instruction
Select 
acc.BRANCH_CODE	BRANCH_CODE,--mapping bank
acc.SOURCE_CODE SOURCE_CODE,--	AMP_SI
acc.SOURCE_REF	SOURCE_REF,--
acc.PRODUCT_CODE PRODUCT_CODE,--	mapping of bank
acc.PRODUCT_TYPE PRODUCT_TYPE,--	Payements,SweepInt, Sweepout,Collection,VariablePayment,RangeBalanceSweep
1 SI_TYPE	,--One to one=1, One to Many=2, Many to One=3,  Many to Many=4
'F' CAL_HOL_EXCP,--	Forward, Backward, Lapse (default=B)
'STANDARD' RATE_TYPE,--	default=STANDARD
(case when vrt.pde in ('H','J') then vrt.jex else null end) EXEC_DAYS,--	
(case when vrt.pde='M' then vrt.jex else null end) EXEC_MTHS,--	
(case when vrt.pde='A' then vrt.jex else null end) EXEC_YRS	,--

(
	case when pde = 'J' then sysdate+1 -- dsam: added 20220421
		 when pde = 'M' then sysdate+30
		 when pde = 'A' then sysdate+365
		 when pde = 'H' then sysdate+7
	end
) FIRST_EXEC_DATE,

(
	case when pde = 'J' then sysdate+2 -- dsam: added 20220421
		 when pde = 'H' then sysdate+14
		 when pde = 'M' then sysdate+60
		 when pde = 'A' then sysdate+730
	end
) NEXT_EXEC_DATE,

(
	case when pde = 'J' then sysdate+1 -- dsam: added 20220421
		 when pde = 'H' then sysdate+7
		 when pde = 'M' then sysdate+30
		 when pde = 'A' then sysdate+365
	end
) FIRST_VALUE_DATE,

(
	case when pde = 'J' then sysdate+2 -- dsam: added 20220421
		 when pde = 'H' then sysdate+14
		 when pde = 'M' then sysdate+60
		 when pde = 'A' then sysdate+730
	end
) NEXT_VALUE_DATE,

/*
vrt.dpe FIRST_EXEC_DATE	,--  First_Exec_Date|Next_Exec_Date|First_Value_Date|Next_Value_Date
NEXT_EXEC_DATE
(
vrt.pde 
, vrt.jex 
, vrt.ope ,
vrt.dpe ,
vrt.dex ,
vrt.dde )NEXT_EXEC_DATE	,-- a corriger
FIRST_VALUE_DATE(vrt.eve,vrt.dpe,'000') FIRST_VALUE_DATE	,--
NEXT_VALUE_DATE('000',NEXT_EXEC_DATE
(
vrt.pde 
, vrt.jex 
, vrt.ope ,
vrt.dpe ,
vrt.dex ,
vrt.dde ),'00'	)  NEXT_VALUE_DATE	,--

*/
'N' MONTH_END_FLAG,--	default=N it depend on instructions
'E' PROCESSING_TIME	,--End of day=default, Begining of day
acc.USER_REF_NUMBER USER_INST_NO	,--USER_ref_no FROM THE MASTER UPLOAD
'A' INST_STATUS,--	DEFAULT = A
'A' AUTH_STATUS,--	Default=A
vrt.dmo LATEST_VERSION_DATE	,--
vrt.dou BOOK_DATE	,--
'' SERIAL_NO	,--
substr(vrt.cli1,1,9) COUNTERPARTY	,--
'' LATEST_CYCLE_NO	,--
vrt.dex LATEST_CYCLE_DATE	,--
'O' CONV_STATUS	,--
NULL ERR_MSG	,--
NULL GEN_MESG	,--default=NULL
Acc.SOURCE_REF INSTRUCTION_NO	,--SOURCE_REF
1 INST_VERSION_NO,--	default=1
NULL OPERATION	,--default=NULL
'SIDTRONL' FUNCTION_ID	,--default=SIDTRONL
Acc.SOURCE_SEQ_NO SOURCE_SEQ_NO	,--
Acc.SOURCE_SEQ_NO UPLOAD_ID	,--same as SOURCE_SEQ_NO
'NEW' ACTION_CODE	,--default=NEW
(case when (vrt.sud is null or vrt.sud <'&DATE_PARAM') then 'N' else (case when sua>='31-JAN-22' then 'O' else 'N' end) end) SUSPEND_EXECUTION,--	default=N
NULL GOAL_REF_NO	,--default=NULL
NULL GROUP_CODE
From Sitb_Upload_Master Acc, bkvrt vrt 
where vrt.eta in ('VA','FO') and vrt.dde>'&DATE_PARAM'  and vrt.eve=acc.contract_ref_no;

commit;

Update Sitb_Upload_Master set CONTRACT_REF_NO=NULL ;
commit;

Update Sitb_Upload_Master set book_date='&DATE_PARAM' ;
commit;

--select * from Sitb_Upload_Master;
--select * from Sitb_Upload_Instruction;


/*
--------
create table si_table 
(cr_account varchar2(18)
,Comm varchar2(25)
);

insert into si_table values('001074200003750761','Credit Line');
commit;
*/


delete from Sitb_Upload_Master where product_code = 'SIBK'; -- dsam: External SI will be handle differently
delete from Sitb_Upload_Instruction where product_code = 'SIBK'; -- dsam: External SI will be handle differently
commit;
update Sitb_Upload_Instruction set  exec_days = null, exec_mths = 1, exec_yrs = null;
commit;